# GitLab CI to build Rust+Mynewt Firmware for PineTime Smart Watch
# Based on https://github.com/lupyuen/pinetime-rust-mynewt/blob/master/.github/workflows/main.yml

# Official language image. Look for the different tagged releases at: https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

build:
  stage: build

  #########################################################################################
  # Checkout

  variables:
    # Clone submodules recursively
    GIT_SUBMODULE_STRATEGY: recursive

  #########################################################################################
  # Download and Cache Dependencies

  before_script:
    # Show files
    - set ; pwd ; ls -l

    # Install Go
    - pushd /tmp    
    - wget -qO- https://golang.org/dl/go1.14.7.linux-amd64.tar.gz | tar -xz
    - popd
    - export PATH=$PATH:/tmp/go/bin
    - go version

    # Install newt
    - source scripts/install-version.sh
    - pushd /tmp
    - git clone --branch $mynewt_version https://github.com/apache/mynewt-newt/
    - cd mynewt-newt/
    - ./build.sh
    - newt/newt version
    - popd
    - export PATH=$PATH:/tmp/mynewt-newt/newt
    - newt version

    # Download Mynewt source files
    # Ignore Error: Error updating "mcuboot": error: The following untracked working tree files would be overwritten by checkout:
    # ext/mbedtls/include/mbedtls/check_config.h
    # ext/mbedtls/include/mbedtls/config.h
    - export PATH=$PATH:/tmp/mynewt-newt/newt
    - newt install -v -f || ls -l repos
    #  Overwrite MCUBoot with newer version
    - source scripts/install-version.sh
    - pushd repos
    - rm -rf mcuboot
    - git clone --branch $mcuboot_version https://github.com/JuulLabs-OSS/mcuboot
    # git clone --branch $mynewt_version https://github.com/apache/mynewt-core
    # git clone --branch $nimble_version https://github.com/apache/mynewt-nimble
    - popd

    # Install Rust Target thumbv7em-none-eabihf
    - rustup default nightly
    - rustup target add thumbv7em-none-eabihf

    # Install Embedded Arm Toolchain arm-none-eabi-gcc
    - pushd /tmp
    - wget -qO- https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2019q3/RC1.1/gcc-arm-none-eabi-8-2019-q3-update-linux.tar.bz2 | tar -xj
    - popd
    - export PATH=$PATH:/tmp/gcc-arm-none-eabi-8-2019-q3-update/bin
    - arm-none-eabi-gcc --version

  #########################################################################################
  # Build Bootloader and Rust+Mynewt Application Firmware

  script:
    # Set PATH
    - export PATH=$PATH:/tmp/go/bin:/tmp/mynewt-newt/newt:/tmp/gcc-arm-none-eabi-8-2019-q3-update/bin

    # Build Bootloader
    - ./scripts/nrf52/build-boot.sh

    # Build Application Firmware
    - ./scripts/build-app.sh

    # Create Application Firmware Image
    - ./scripts/nrf52/image-app.sh

  #########################################################################################
  # Upload Bootloader and Application Firmware

  artifacts:
    paths:
      - bin

  #########################################################################################
  # Cache Outputs

  cache:
    paths:
      - "*.o"
      - /tmp/go
      - /tmp/mynewt-newt
      - /tmp/gcc-arm-none-eabi-8-2019-q3-update

#########################################################################################
# Run Tests

test:
  stage: test
  script:
    - echo "Done!"
