In archive target/thumbv7m-none-eabi/release/libmylib.rlib:

mylib-9b5f404664613177.mylib.9ieylas6-cgu.0.rcgu.o:     file format elf32-littlearm

SYMBOL TABLE:
00000000 l    df *ABS*	00000000 mylib.9ieylas6-cgu.0
00000000 l       .debug_str	00000000 
00000041 l       .debug_str	00000000 
0000004c l       .debug_str	00000000 
0000006f l       .debug_str	00000000 
00000075 l       .debug_str	00000000 
0000007c l       .debug_str	00000000 
0000007f l       .debug_str	00000000 
00000086 l       .debug_str	00000000 
00000098 l       .debug_str	00000000 
000000a1 l       .debug_str	00000000 
000000b0 l       .debug_str	00000000 
000000b4 l       .debug_str	00000000 
000000bc l       .debug_str	00000000 
000000c1 l       .debug_str	00000000 
000000c8 l       .debug_str	00000000 
000000cc l       .debug_str	00000000 
000000d1 l       .debug_str	00000000 
000000d5 l       .debug_str	00000000 
000000db l       .debug_str	00000000 
000000e2 l       .debug_str	00000000 
000000e5 l       .debug_str	00000000 
000000f1 l       .debug_str	00000000 
000000f9 l       .debug_str	00000000 
000000fd l       .debug_str	00000000 
00000100 l       .debug_str	00000000 
0000010b l       .debug_str	00000000 
00000116 l       .debug_str	00000000 
0000011d l       .debug_str	00000000 
00000134 l       .debug_str	00000000 
00000195 l       .debug_str	00000000 
00000197 l       .debug_str	00000000 
0000019c l       .debug_str	00000000 
000001a0 l       .debug_str	00000000 
00000209 l       .debug_str	00000000 
00000214 l       .debug_str	00000000 
00000262 l       .debug_str	00000000 
000002b8 l       .debug_str	00000000 
000002c2 l       .debug_str	00000000 
00000306 l       .debug_str	00000000 
00000352 l       .debug_str	00000000 
0000035b l       .debug_str	00000000 
0000036b l       .debug_str	00000000 
00000373 l       .debug_str	00000000 
000003cf l       .debug_str	00000000 
00000433 l       .debug_str	00000000 
0000043f l       .debug_str	00000000 
00000448 l       .debug_str	00000000 
00000454 l       .debug_str	00000000 
00000460 l       .debug_str	00000000 
00000469 l       .debug_str	00000000 
00000471 l       .debug_str	00000000 
0000047b l       .debug_str	00000000 
00000483 l       .debug_str	00000000 
0000048d l       .debug_str	00000000 
000004a2 l       .debug_str	00000000 
000004a9 l       .debug_str	00000000 
000004d0 l       .debug_str	00000000 
000004d7 l       .debug_str	00000000 
000004df l       .debug_str	00000000 
000004e9 l       .debug_str	00000000 
000004f4 l       .debug_str	00000000 
000004fd l       .debug_str	00000000 
00000508 l       .debug_str	00000000 
00000514 l       .debug_str	00000000 
00000518 l       .debug_str	00000000 
00000521 l       .debug_str	00000000 
00000528 l       .debug_str	00000000 
00000530 l       .debug_str	00000000 
00000538 l       .debug_str	00000000 
00000542 l       .debug_str	00000000 
00000548 l       .debug_str	00000000 
0000054f l       .debug_str	00000000 
00000556 l       .debug_str	00000000 
00000583 l       .debug_str	00000000 
000005b8 l       .debug_str	00000000 
000005be l       .debug_str	00000000 
000005c4 l       .debug_str	00000000 
000005d3 l       .debug_str	00000000 
000005e3 l       .debug_str	00000000 
000005f3 l       .debug_str	00000000 
000005fb l       .debug_str	00000000 
0000062b l       .debug_str	00000000 
00000690 l       .debug_str	00000000 
000006fd l       .debug_str	00000000 
00000704 l       .debug_str	00000000 
0000070c l       .debug_str	00000000 
00000715 l       .debug_str	00000000 
00000733 l       .debug_str	00000000 
00000743 l       .debug_str	00000000 
00000751 l       .debug_str	00000000 
0000075c l       .debug_str	00000000 
00000769 l       .debug_str	00000000 
00000778 l       .debug_str	00000000 
0000078e l       .debug_str	00000000 
00000798 l       .debug_str	00000000 
000007a1 l       .debug_str	00000000 
000007aa l       .debug_str	00000000 
000007d7 l       .debug_str	00000000 
000007ed l       .debug_str	00000000 
000007f8 l       .debug_str	00000000 
0000080e l       .debug_str	00000000 
00000816 l       .debug_str	00000000 
0000083e l       .debug_str	00000000 
00000855 l       .debug_str	00000000 
0000085a l       .debug_str	00000000 
00000862 l       .debug_str	00000000 
0000086b l       .debug_str	00000000 
00000874 l       .debug_str	00000000 
0000087d l       .debug_str	00000000 
00000885 l       .debug_str	00000000 
0000088c l       .debug_str	00000000 
00000898 l       .debug_str	00000000 
000008a3 l       .debug_str	00000000 
000008ab l       .debug_str	00000000 
000008b3 l       .debug_str	00000000 
000009bd l       .debug_str	00000000 
00000acf l       .debug_str	00000000 
00000add l       .debug_str	00000000 
00000ae8 l       .debug_str	00000000 
00000af2 l       .debug_str	00000000 
00000b06 l       .debug_str	00000000 
00000b11 l       .debug_str	00000000 
00000b46 l       .debug_str	00000000 
00000bcf l       .debug_str	00000000 
00000c60 l       .debug_str	00000000 
00000c6e l       .debug_str	00000000 
00000cd4 l       .debug_str	00000000 
00000d42 l       .debug_str	00000000 
00000d58 l       .debug_str	00000000 
00000d68 l       .debug_str	00000000 
00000d77 l       .debug_str	00000000 
00000d7b l       .debug_str	00000000 
00000d82 l       .debug_str	00000000 
00000d88 l       .debug_str	00000000 
00000d8c l       .debug_str	00000000 
00000d92 l       .debug_str	00000000 
00000d98 l       .debug_str	00000000 
00000da4 l       .debug_str	00000000 
00000dac l       .debug_str	00000000 
00000db2 l       .debug_str	00000000 
00000dba l       .debug_str	00000000 
00000dc0 l       .debug_str	00000000 
00000de3 l       .debug_str	00000000 
00000df3 l       .debug_str	00000000 
00000e2d l       .debug_str	00000000 
00000e74 l       .debug_str	00000000 
00000ec3 l       .debug_str	00000000 
00000ec7 l       .debug_str	00000000 
00000ecd l       .debug_str	00000000 
00000ed3 l       .debug_str	00000000 
00000ed9 l       .debug_str	00000000 
00000eeb l       .debug_str	00000000 
00000f27 l       .debug_str	00000000 
00000f70 l       .debug_str	00000000 
00000fc1 l       .debug_str	00000000 
00000fc5 l       .debug_str	00000000 
00000fcb l       .debug_str	00000000 
00000fd1 l       .debug_str	00000000 
00000fd7 l       .debug_str	00000000 
00000fe9 l       .debug_str	00000000 
00001025 l       .debug_str	00000000 
0000106e l       .debug_str	00000000 
000010bf l       .debug_str	00000000 
000010c3 l       .debug_str	00000000 
000010c9 l       .debug_str	00000000 
000010cf l       .debug_str	00000000 
000010d5 l       .debug_str	00000000 
000010db l       .debug_str	00000000 
000010ec l       .debug_str	00000000 
00001127 l       .debug_str	00000000 
0000116f l       .debug_str	00000000 
000011bf l       .debug_str	00000000 
000011c4 l       .debug_str	00000000 
000011c9 l       .debug_str	00000000 
000011cd l       .debug_str	00000000 
000011d3 l       .debug_str	00000000 
000011d9 l       .debug_str	00000000 
000011df l       .debug_str	00000000 
000011f0 l       .debug_str	00000000 
0000122b l       .debug_str	00000000 
00001273 l       .debug_str	00000000 
000012c3 l       .debug_str	00000000 
000012c7 l       .debug_str	00000000 
000012d0 l       .debug_str	00000000 
000012e1 l       .debug_str	00000000 
0000131c l       .debug_str	00000000 
00001364 l       .debug_str	00000000 
000013b4 l       .debug_str	00000000 
000013b9 l       .debug_str	00000000 
000013bd l       .debug_str	00000000 
000013c6 l       .debug_str	00000000 
000013cd l       .debug_str	00000000 
000013d5 l       .debug_str	00000000 
000013e7 l       .debug_str	00000000 
00001423 l       .debug_str	00000000 
0000146c l       .debug_str	00000000 
000014bd l       .debug_str	00000000 
000014c1 l       .debug_str	00000000 
000014c7 l       .debug_str	00000000 
000014cd l       .debug_str	00000000 
000014d3 l       .debug_str	00000000 
000014d9 l       .debug_str	00000000 
000014e1 l       .debug_str	00000000 
000014ef l       .debug_str	00000000 
000014fe l       .debug_str	00000000 
0000150f l       .debug_str	00000000 
0000151a l       .debug_str	00000000 
00001525 l       .debug_str	00000000 
00001530 l       .debug_str	00000000 
00001537 l       .debug_str	00000000 
0000155a l       .debug_str	00000000 
0000156c l       .debug_str	00000000 
000015a8 l       .debug_str	00000000 
000015f1 l       .debug_str	00000000 
00001642 l       .debug_str	00000000 
00001646 l       .debug_str	00000000 
00001650 l       .debug_str	00000000 
00001662 l       .debug_str	00000000 
0000169e l       .debug_str	00000000 
000016e7 l       .debug_str	00000000 
00001738 l       .debug_str	00000000 
0000173d l       .debug_str	00000000 
00001747 l       .debug_str	00000000 
00001759 l       .debug_str	00000000 
00001795 l       .debug_str	00000000 
000017de l       .debug_str	00000000 
0000182f l       .debug_str	00000000 
00001843 l       .debug_str	00000000 
00001847 l       .debug_str	00000000 
00001855 l       .debug_str	00000000 
00001865 l       .debug_str	00000000 
0000186e l       .debug_str	00000000 
00001879 l       .debug_str	00000000 
00001888 l       .debug_str	00000000 
0000189d l       .debug_str	00000000 
000018d5 l       .debug_str	00000000 
00001980 l       .debug_str	00000000 
00001a33 l       .debug_str	00000000 
00001a3e l       .debug_str	00000000 
00001a47 l       .debug_str	00000000 
00001a68 l       .debug_str	00000000 
00001a7b l       .debug_str	00000000 
00001ab8 l       .debug_str	00000000 
00001b49 l       .debug_str	00000000 
00001be2 l       .debug_str	00000000 
00001bfe l       .debug_str	00000000 
00001c51 l       .debug_str	00000000 
00001cac l       .debug_str	00000000 
00001cc9 l       .debug_str	00000000 
00001cdd l       .debug_str	00000000 
00001d30 l       .debug_str	00000000 
00001d8b l       .debug_str	00000000 
00001da1 l       .debug_str	00000000 
00001db5 l       .debug_str	00000000 
00001e03 l       .debug_str	00000000 
00001e59 l       .debug_str	00000000 
00001e62 l       .debug_str	00000000 
00001e70 l       .debug_str	00000000 
00001ea8 l       .debug_str	00000000 
00001eae l       .debug_str	00000000 
00001eb6 l       .debug_str	00000000 
00001ebd l       .debug_str	00000000 
00001ec5 l       .debug_str	00000000 
00001ed0 l       .debug_str	00000000 
00001ed8 l       .debug_str	00000000 
00001ee7 l       .debug_str	00000000 
00001eeb l       .debug_str	00000000 
00001ef6 l       .debug_str	00000000 
00001f02 l       .debug_str	00000000 
00001f0d l       .debug_str	00000000 
00001f1e l       .debug_str	00000000 
00001f24 l       .debug_str	00000000 
00001f2c l       .debug_str	00000000 
00001f33 l       .debug_str	00000000 
00001f3d l       .debug_str	00000000 
00001f45 l       .debug_str	00000000 
00001f4d l       .debug_str	00000000 
00001f76 l       .debug_str	00000000 
00001f81 l       .debug_str	00000000 
00001f8d l       .debug_str	00000000 
00001f95 l       .debug_str	00000000 
00001f9e l       .debug_str	00000000 
00001fa9 l       .debug_str	00000000 
00001fb0 l       .debug_str	00000000 
00001fbb l       .debug_str	00000000 
00001fc6 l       .debug_str	00000000 
00001fd6 l       .debug_str	00000000 
00001fe0 l       .debug_str	00000000 
00001fe6 l       .debug_str	00000000 
0000200f l       .debug_str	00000000 
0000204e l       .debug_str	00000000 
00002095 l       .debug_str	00000000 
0000209c l       .debug_str	00000000 
000020a4 l       .debug_str	00000000 
000020bb l       .debug_str	00000000 
000020c4 l       .debug_str	00000000 
000020d4 l       .debug_str	00000000 
0000210e l       .debug_str	00000000 
00002123 l       .debug_str	00000000 
0000212c l       .debug_str	00000000 
00002190 l       .debug_str	00000000 
000021fc l       .debug_str	00000000 
00002206 l       .debug_str	00000000 
00002216 l       .debug_str	00000000 
0000222b l       .debug_str	00000000 
00002233 l       .debug_str	00000000 
0000229e l       .debug_str	00000000 
00002311 l       .debug_str	00000000 
00002318 l       .debug_str	00000000 
00002320 l       .debug_str	00000000 
0000233e l       .debug_str	00000000 
0000234e l       .debug_str	00000000 
00002388 l       .debug_str	00000000 
0000239d l       .debug_str	00000000 
000023b0 l       .debug_str	00000000 
000023c5 l       .debug_str	00000000 
000023cc l       .debug_str	00000000 
000023e1 l       .debug_str	00000000 
00002412 l       .debug_str	00000000 
00002495 l       .debug_str	00000000 
00002520 l       .debug_str	00000000 
00002527 l       .debug_str	00000000 
0000252f l       .debug_str	00000000 
0000254d l       .debug_str	00000000 
0000255d l       .debug_str	00000000 
0000259f l       .debug_str	00000000 
000025a9 l       .debug_str	00000000 
000025b6 l       .debug_str	00000000 
000025ec l       .debug_str	00000000 
000025ff l       .debug_str	00000000 
0000263b l       .debug_str	00000000 
0000264c l       .debug_str	00000000 
00002651 l       .debug_str	00000000 
0000268b l       .debug_str	00000000 
00002698 l       .debug_str	00000000 
0000269c l       .debug_str	00000000 
000026a8 l       .debug_str	00000000 
000026de l       .debug_str	00000000 
000026e5 l       .debug_str	00000000 
000026e8 l       .debug_str	00000000 
000026ec l       .debug_str	00000000 
000026f3 l       .debug_str	00000000 
000026f7 l       .debug_str	00000000 
000026fa l       .debug_str	00000000 
000026fd l       .debug_str	00000000 
00002702 l       .debug_str	00000000 
00002708 l       .debug_str	00000000 
0000270f l       .debug_str	00000000 
00002717 l       .debug_str	00000000 
00002721 l       .debug_str	00000000 
00002729 l       .debug_str	00000000 
00002734 l       .debug_str	00000000 
0000273f l       .debug_str	00000000 
0000274c l       .debug_str	00000000 
00002757 l       .debug_str	00000000 
0000275f l       .debug_str	00000000 
0000276a l       .debug_str	00000000 
00002775 l       .debug_str	00000000 
0000277f l       .debug_str	00000000 
0000278a l       .debug_str	00000000 
00002795 l       .debug_str	00000000 
000027a2 l       .debug_str	00000000 
000027ae l       .debug_str	00000000 
000027bb l       .debug_str	00000000 
000027c9 l       .debug_str	00000000 
000027d3 l       .debug_str	00000000 
000027e0 l       .debug_str	00000000 
000027ec l       .debug_str	00000000 
000027f0 l       .debug_str	00000000 
000027f9 l       .debug_str	00000000 
00002856 l       .debug_str	00000000 
0000285b l       .debug_str	00000000 
00002860 l       .debug_str	00000000 
00002862 l       .debug_str	00000000 
00002868 l       .debug_str	00000000 
0000286d l       .debug_str	00000000 
00002872 l       .debug_str	00000000 
00002878 l       .debug_str	00000000 
0000287e l       .debug_str	00000000 
0000288c l       .debug_str	00000000 
00002896 l       .debug_str	00000000 
0000289a l       .debug_str	00000000 
000028a2 l       .debug_str	00000000 
000028aa l       .debug_str	00000000 
000028b1 l       .debug_str	00000000 
000028bd l       .debug_str	00000000 
000028c8 l       .debug_str	00000000 
000028cf l       .debug_str	00000000 
000028d5 l       .debug_str	00000000 
000028d9 l       .debug_str	00000000 
000028df l       .debug_str	00000000 
000028e5 l       .debug_str	00000000 
000028e8 l       .debug_str	00000000 
000028f7 l       .debug_str	00000000 
000028fb l       .debug_str	00000000 
00002904 l       .debug_str	00000000 
00002910 l       .debug_str	00000000 
00002929 l       .debug_str	00000000 
0000292e l       .debug_str	00000000 
0000293f l       .debug_str	00000000 
00002949 l       .debug_str	00000000 
000029a7 l       .debug_str	00000000 
000029b2 l       .debug_str	00000000 
000029cf l       .debug_str	00000000 
000029d3 l       .debug_str	00000000 
000029db l       .debug_str	00000000 
000029f2 l       .debug_str	00000000 
00002a16 l       .debug_str	00000000 
00002a32 l       .debug_str	00000000 
00002a37 l       .debug_str	00000000 
00002a40 l       .debug_str	00000000 
00002a47 l       .debug_str	00000000 
00002a60 l       .debug_str	00000000 
00002a6a l       .debug_str	00000000 
00002a84 l       .debug_str	00000000 
00002ae0 l       .debug_str	00000000 
00002ae4 l       .debug_str	00000000 
00002ae8 l       .debug_str	00000000 
00002af1 l       .debug_str	00000000 
00002af6 l       .debug_str	00000000 
00002aff l       .debug_str	00000000 
00002b41 l       .debug_str	00000000 
00002b8b l       .debug_str	00000000 
00002b92 l       .debug_str	00000000 
00002ba0 l       .debug_str	00000000 
00002bad l       .debug_str	00000000 
00002bd5 l       .debug_str	00000000 
00002c09 l       .debug_str	00000000 
00002c11 l       .debug_str	00000000 
00002c1b l       .debug_str	00000000 
00002c21 l       .debug_str	00000000 
00002c26 l       .debug_str	00000000 
00002c2e l       .debug_str	00000000 
00002c37 l       .debug_str	00000000 
00002c4d l       .debug_str	00000000 
00002c6b l       .debug_str	00000000 
00002c74 l       .debug_str	00000000 
00002c7d l       .debug_str	00000000 
00002c93 l       .debug_str	00000000 
00002cb1 l       .debug_str	00000000 
00002cb6 l       .debug_str	00000000 
00002cba l       .debug_str	00000000 
00002cc3 l       .debug_str	00000000 
00002cd9 l       .debug_str	00000000 
00002cf7 l       .debug_str	00000000 
00002cfe l       .debug_str	00000000 
00002d13 l       .debug_str	00000000 
00002d30 l       .debug_str	00000000 
00002d38 l       .debug_str	00000000 
00002d42 l       .debug_str	00000000 
00002d59 l       .debug_str	00000000 
00002d78 l       .debug_str	00000000 
00002d82 l       .debug_str	00000000 
00002d88 l       .debug_str	00000000 
00002d95 l       .debug_str	00000000 
00002d99 l       .debug_str	00000000 
00002da1 l       .debug_str	00000000 
00002df6 l       .debug_str	00000000 
00002e53 l       .debug_str	00000000 
00002e5b l       .debug_str	00000000 
00002e60 l       .debug_str	00000000 
00002e6d l       .debug_str	00000000 
00002e73 l       .debug_str	00000000 
00002e7c l       .debug_str	00000000 
00002ea5 l       .debug_str	00000000 
00002efa l       .debug_str	00000000 
00002f57 l       .debug_str	00000000 
00002f60 l       .debug_str	00000000 
00002f89 l       .debug_str	00000000 
00002fde l       .debug_str	00000000 
0000303b l       .debug_str	00000000 
00003045 l       .debug_str	00000000 
0000306e l       .debug_str	00000000 
000030c3 l       .debug_str	00000000 
00003120 l       .debug_str	00000000 
00003126 l       .debug_str	00000000 
0000314f l       .debug_str	00000000 
000031a4 l       .debug_str	00000000 
00003201 l       .debug_str	00000000 
0000320a l       .debug_str	00000000 
00003233 l       .debug_str	00000000 
00003288 l       .debug_str	00000000 
000032e5 l       .debug_str	00000000 
00003300 l       .debug_str	00000000 
00003306 l       .debug_str	00000000 
0000330f l       .debug_str	00000000 
00003316 l       .debug_str	00000000 
00003323 l       .debug_str	00000000 
0000335c l       .debug_str	00000000 
0000339d l       .debug_str	00000000 
000033a4 l       .debug_str	00000000 
000033b7 l       .debug_str	00000000 
000033d2 l       .debug_str	00000000 
000033ec l       .debug_str	00000000 
000033f1 l       .debug_str	00000000 
00003402 l       .debug_str	00000000 
0000341b l       .debug_str	00000000 
0000342c l       .debug_str	00000000 
00003445 l       .debug_str	00000000 
00003456 l       .debug_str	00000000 
0000346f l       .debug_str	00000000 
00003481 l       .debug_str	00000000 
0000349b l       .debug_str	00000000 
000034ab l       .debug_str	00000000 
000034c3 l       .debug_str	00000000 
000034c9 l       .debug_str	00000000 
000034e3 l       .debug_str	00000000 
000034e7 l       .debug_str	00000000 
000034eb l       .debug_str	00000000 
000034f0 l       .debug_str	00000000 
000034fc l       .debug_str	00000000 
0000352e l       .debug_str	00000000 
00003538 l       .debug_str	00000000 
00003544 l       .debug_str	00000000 
00003576 l       .debug_str	00000000 
0000357b l       .debug_str	00000000 
00003582 l       .debug_str	00000000 
000035ab l       .debug_str	00000000 
000035d3 l       .debug_str	00000000 
00003623 l       .debug_str	00000000 
0000364b l       .debug_str	00000000 
0000368d l       .debug_str	00000000 
000036b5 l       .debug_str	00000000 
000036e9 l       .debug_str	00000000 
00003711 l       .debug_str	00000000 
00003752 l       .debug_str	00000000 
0000377a l       .debug_str	00000000 
000037ad l       .debug_str	00000000 
000037d5 l       .debug_str	00000000 
00003801 l       .debug_str	00000000 
00003806 l       .debug_str	00000000 
0000380c l       .debug_str	00000000 
00003816 l       .debug_str	00000000 
0000381f l       .debug_str	00000000 
00003828 l       .debug_str	00000000 
00003833 l       .debug_str	00000000 
0000383d l       .debug_str	00000000 
0000386b l       .debug_str	00000000 
00003883 l       .debug_str	00000000 
0000388d l       .debug_str	00000000 
000038b7 l       .debug_str	00000000 
000038bf l       .debug_str	00000000 
000038c6 l       .debug_str	00000000 
000038f1 l       .debug_str	00000000 
00003921 l       .debug_str	00000000 
0000393a l       .debug_str	00000000 
00003945 l       .debug_str	00000000 
0000396d l       .debug_str	00000000 
0000399b l       .debug_str	00000000 
000039a5 l       .debug_str	00000000 
000039ad l       .debug_str	00000000 
000039b4 l       .debug_str	00000000 
000039bb l       .debug_str	00000000 
000039c0 l       .debug_str	00000000 
000039ea l       .debug_str	00000000 
00003a19 l       .debug_str	00000000 
00003a31 l       .debug_str	00000000 
00003a3b l       .debug_str	00000000 
00003a63 l       .debug_str	00000000 
00003a90 l       .debug_str	00000000 
00003ab8 l       .debug_str	00000000 
00003ae2 l       .debug_str	00000000 
00003aea l       .debug_str	00000000 
00003af3 l       .debug_str	00000000 
00003b01 l       .debug_str	00000000 
00003b08 l       .debug_str	00000000 
00003b0f l       .debug_str	00000000 
00003b1f l       .debug_str	00000000 
00003b28 l       .debug_str	00000000 
00003b36 l       .debug_str	00000000 
00003b44 l       .debug_str	00000000 
00003b50 l       .debug_str	00000000 
00003b5c l       .debug_str	00000000 
00003b65 l       .debug_str	00000000 
00003b74 l       .debug_str	00000000 
00003b7c l       .debug_str	00000000 
00003b95 l       .debug_str	00000000 
00003ba6 l       .debug_str	00000000 
00003bae l       .debug_str	00000000 
00003bc8 l       .debug_str	00000000 
00003bd4 l       .debug_str	00000000 
00003c00 l       .debug_str	00000000 
00003c19 l       .debug_str	00000000 
00003c24 l       .debug_str	00000000 
00003c4f l       .debug_str	00000000 
00003c58 l       .debug_str	00000000 
00003c73 l       .debug_str	00000000 
00003c80 l       .debug_str	00000000 
00003cad l       .debug_str	00000000 
00003cb5 l       .debug_str	00000000 
00003cdd l       .debug_str	00000000 
00003cf3 l       .debug_str	00000000 
00003cfe l       .debug_str	00000000 
00003d02 l       .debug_str	00000000 
00003d1d l       .debug_str	00000000 
00003d25 l       .debug_str	00000000 
00003d4d l       .debug_str	00000000 
00003d78 l       .debug_str	00000000 
00003da0 l       .debug_str	00000000 
00003dce l       .debug_str	00000000 
00003df6 l       .debug_str	00000000 
00003e29 l       .debug_str	00000000 
00003e51 l       .debug_str	00000000 
00003e7c l       .debug_str	00000000 
00003e85 l       .debug_str	00000000 
00003e9a l       .debug_str	00000000 
00003ea5 l       .debug_str	00000000 
00003eac l       .debug_str	00000000 
00003ed4 l       .debug_str	00000000 
00003efe l       .debug_str	00000000 
00003f26 l       .debug_str	00000000 
00003f61 l       .debug_str	00000000 
00003f89 l       .debug_str	00000000 
00003fc6 l       .debug_str	00000000 
00003fee l       .debug_str	00000000 
0000402e l       .debug_str	00000000 
00004056 l       .debug_str	00000000 
0000408a l       .debug_str	00000000 
00004093 l       .debug_str	00000000 
000040a6 l       .debug_str	00000000 
000040b1 l       .debug_str	00000000 
000040c1 l       .debug_str	00000000 
000040dd l       .debug_str	00000000 
000040eb l       .debug_str	00000000 
00004113 l       .debug_str	00000000 
0000414e l       .debug_str	00000000 
00004153 l       .debug_str	00000000 
0000415f l       .debug_str	00000000 
00004161 l       .debug_str	00000000 
00004164 l       .debug_str	00000000 
00004175 l       .debug_str	00000000 
0000418e l       .debug_str	00000000 
00004192 l       .debug_str	00000000 
0000419c l       .debug_str	00000000 
000041a1 l       .debug_str	00000000 
000041a8 l       .debug_str	00000000 
000041b0 l       .debug_str	00000000 
000041b8 l       .debug_str	00000000 
000041bf l       .debug_str	00000000 
000041c6 l       .debug_str	00000000 
000041ed l       .debug_str	00000000 
00004240 l       .debug_str	00000000 
0000429b l       .debug_str	00000000 
000042b4 l       .debug_str	00000000 
000042bf l       .debug_str	00000000 
000042ee l       .debug_str	00000000 
00004322 l       .debug_str	00000000 
00004378 l       .debug_str	00000000 
000043d6 l       .debug_str	00000000 
000043fe l       .debug_str	00000000 
00004441 l       .debug_str	00000000 
00004450 l       .debug_str	00000000 
0000445b l       .debug_str	00000000 
0000446a l       .debug_str	00000000 
0000447f l       .debug_str	00000000 
00004497 l       .debug_str	00000000 
000044ea l       .debug_str	00000000 
00004545 l       .debug_str	00000000 
0000455a l       .debug_str	00000000 
00004573 l       .debug_str	00000000 
0000459b l       .debug_str	00000000 
000045e1 l       .debug_str	00000000 
00004613 l       .debug_str	00000000 
00004621 l       .debug_str	00000000 
00004625 l       .debug_str	00000000 
0000462b l       .debug_str	00000000 
00004639 l       .debug_str	00000000 
00004677 l       .debug_str	00000000 
00004687 l       .debug_str	00000000 
0000468b l       .debug_str	00000000 
00004690 l       .debug_str	00000000 
00004695 l       .debug_str	00000000 
0000469b l       .debug_str	00000000 
000046ab l       .debug_str	00000000 
000046b7 l       .debug_str	00000000 
000046c3 l       .debug_str	00000000 
000046cf l       .debug_str	00000000 
000046dc l       .debug_str	00000000 
000046e8 l       .debug_str	00000000 
000046f6 l       .debug_str	00000000 
0000470d l       .debug_str	00000000 
00004722 l       .debug_str	00000000 
00004725 l       .debug_str	00000000 
00004745 l       .debug_str	00000000 
0000474e l       .debug_str	00000000 
00004788 l       .debug_str	00000000 
00004799 l       .debug_str	00000000 
0000479b l       .debug_str	00000000 
000047ca l       .debug_str	00000000 
000047d5 l       .debug_str	00000000 
000047ef l       .debug_str	00000000 
000047fb l       .debug_str	00000000 
00004805 l       .debug_str	00000000 
0000480b l       .debug_str	00000000 
00004810 l       .debug_str	00000000 
00004821 l       .debug_str	00000000 
0000482a l       .debug_str	00000000 
00004832 l       .debug_str	00000000 
0000483c l       .debug_str	00000000 
00004849 l       .debug_str	00000000 
00004890 l       .debug_str	00000000 
000048ae l       .debug_str	00000000 
000048b7 l       .debug_str	00000000 
000048e7 l       .debug_str	00000000 
000048f0 l       .debug_str	00000000 
000048f6 l       .debug_str	00000000 
0000493a l       .debug_str	00000000 
00004955 l       .debug_str	00000000 
0000495d l       .debug_str	00000000 
00004966 l       .debug_str	00000000 
00004970 l       .debug_str	00000000 
00004975 l       .debug_str	00000000 
0000497a l       .debug_str	00000000 
0000497f l       .debug_str	00000000 
0000498d l       .debug_str	00000000 
00004997 l       .debug_str	00000000 
00004a1a l       .debug_str	00000000 
00004a24 l       .debug_str	00000000 
00004a2a l       .debug_str	00000000 
00004a30 l       .debug_str	00000000 
00004a34 l       .debug_str	00000000 
00004a41 l       .debug_str	00000000 
00004ac7 l       .debug_str	00000000 
00004ad6 l       .debug_str	00000000 
00004ad8 l       .debug_str	00000000 
00004b4d l       .debug_str	00000000 
00004b78 l       .debug_str	00000000 
00004b7e l       .debug_str	00000000 
00004b85 l       .debug_str	00000000 
00004b91 l       .debug_str	00000000 
00004b99 l       .debug_str	00000000 
00004ba2 l       .debug_str	00000000 
00004ba7 l       .debug_str	00000000 
00004baa l       .debug_str	00000000 
00004bb3 l       .debug_str	00000000 
00004bba l       .debug_str	00000000 
00004bbd l       .debug_str	00000000 
00004bc3 l       .debug_str	00000000 
00004bcd l       .debug_str	00000000 
00004bd5 l       .debug_str	00000000 
00004bdb l       .debug_str	00000000 
00004be6 l       .debug_str	00000000 
00004bef l       .debug_str	00000000 
00004c12 l       .debug_str	00000000 
00004c31 l       .debug_str	00000000 
00004c58 l       .debug_str	00000000 
00004c62 l       .debug_str	00000000 
00004c94 l       .debug_str	00000000 
00004c9b l       .debug_str	00000000 
00004cd7 l       .debug_str	00000000 
00004cea l       .debug_str	00000000 
00004cf0 l       .debug_str	00000000 
00004d34 l       .debug_str	00000000 
00004d4a l       .debug_str	00000000 
00004d53 l       .debug_str	00000000 
00004d57 l       .debug_str	00000000 
00004d99 l       .debug_str	00000000 
00004dab l       .debug_str	00000000 
00004db4 l       .debug_str	00000000 
00004db8 l       .debug_str	00000000 
00004de2 l       .debug_str	00000000 
00004de7 l       .debug_str	00000000 
00004e2f l       .debug_str	00000000 
00004e38 l       .debug_str	00000000 
00004e80 l       .debug_str	00000000 
00004e88 l       .debug_str	00000000 
00004f00 l       .debug_str	00000000 
00004f08 l       .debug_str	00000000 
00004f7f l       .debug_str	00000000 
00005014 l       .debug_str	00000000 
0000509b l       .debug_str	00000000 
00005113 l       .debug_str	00000000 
00005198 l       .debug_str	00000000 
0000520f l       .debug_str	00000000 
0000527f l       .debug_str	00000000 
000052f1 l       .debug_str	00000000 
00005362 l       .debug_str	00000000 
000053d0 l       .debug_str	00000000 
0000543f l       .debug_str	00000000 
000054b1 l       .debug_str	00000000 
00005528 l       .debug_str	00000000 
00005597 l       .debug_str	00000000 
00005605 l       .debug_str	00000000 
0000568c l       .debug_str	00000000 
0000570b l       .debug_str	00000000 
0000578c l       .debug_str	00000000 
00005810 l       .debug_str	00000000 
00005897 l       .debug_str	00000000 
000058a3 l       .debug_str	00000000 
000058af l       .debug_str	00000000 
000058c4 l       .debug_str	00000000 
0000593c l       .debug_str	00000000 
000059bb l       .debug_str	00000000 
00005a01 l       .debug_str	00000000 
00005a17 l       .debug_str	00000000 
00005a9f l       .debug_str	00000000 
00005b2a l       .debug_str	00000000 
00005bbc l       .debug_str	00000000 
00005bc1 l       .debug_str	00000000 
00005c00 l       .debug_str	00000000 
00005c11 l       .debug_str	00000000 
00005c4c l       .debug_str	00000000 
00005c5e l       .debug_str	00000000 
00005c63 l       .debug_str	00000000 
00005c65 l       .debug_str	00000000 
00005c77 l       .debug_str	00000000 
00005c7d l       .debug_str	00000000 
00005ce2 l       .debug_str	00000000 
00005cea l       .debug_str	00000000 
00005cef l       .debug_str	00000000 
00005cfc l       .debug_str	00000000 
00005d09 l       .debug_str	00000000 
00005d10 l       .debug_str	00000000 
00005d20 l       .debug_str	00000000 
00005d32 l       .debug_str	00000000 
00005d3e l       .debug_str	00000000 
00005d43 l       .debug_str	00000000 
00005d4b l       .debug_str	00000000 
00005d4f l       .debug_str	00000000 
00005d54 l       .debug_str	00000000 
00005d5c l       .debug_str	00000000 
00005d72 l       .debug_str	00000000 
00005d90 l       .debug_str	00000000 
00005d99 l       .debug_str	00000000 
00005d9e l       .debug_str	00000000 
00005da3 l       .debug_str	00000000 
00005da7 l       .debug_str	00000000 
00005db0 l       .debug_str	00000000 
00005dba l       .debug_str	00000000 
00005dd2 l       .debug_str	00000000 
00005de9 l       .debug_str	00000000 
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.11	00000010 .Lanon.9efeb2f06c0a343721ec0c21943e311a.11
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.13	00000018 .Lanon.9efeb2f06c0a343721ec0c21943e311a.13
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.14	00000011 .Lanon.9efeb2f06c0a343721ec0c21943e311a.14
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.15	00000018 .Lanon.9efeb2f06c0a343721ec0c21943e311a.15
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.17	00000018 .Lanon.9efeb2f06c0a343721ec0c21943e311a.17
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.18	00000016 .Lanon.9efeb2f06c0a343721ec0c21943e311a.18
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.2	00000018 .Lanon.9efeb2f06c0a343721ec0c21943e311a.2
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.20	00000018 .Lanon.9efeb2f06c0a343721ec0c21943e311a.20
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.21	00000018 .Lanon.9efeb2f06c0a343721ec0c21943e311a.21
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.22	00000019 .Lanon.9efeb2f06c0a343721ec0c21943e311a.22
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.23	0000000a .Lanon.9efeb2f06c0a343721ec0c21943e311a.23
00000000 l     O .rodata.cst8	00000008 .Lanon.9efeb2f06c0a343721ec0c21943e311a.24
00000000 l     O .rodata.cst16	00000010 .Lanon.9efeb2f06c0a343721ec0c21943e311a.25
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.26	00000010 .Lanon.9efeb2f06c0a343721ec0c21943e311a.26
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.28	00000018 .Lanon.9efeb2f06c0a343721ec0c21943e311a.28
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.29	00000010 .Lanon.9efeb2f06c0a343721ec0c21943e311a.29
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.3	0000000a .Lanon.9efeb2f06c0a343721ec0c21943e311a.3
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.30	00000010 .Lanon.9efeb2f06c0a343721ec0c21943e311a.30
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.31	00000011 .Lanon.9efeb2f06c0a343721ec0c21943e311a.31
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.32	00000011 .Lanon.9efeb2f06c0a343721ec0c21943e311a.32
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.33	00000010 .Lanon.9efeb2f06c0a343721ec0c21943e311a.33
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.34	00000001 .Lanon.9efeb2f06c0a343721ec0c21943e311a.34
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.36	00000018 .Lanon.9efeb2f06c0a343721ec0c21943e311a.36
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.37	00000010 .Lanon.9efeb2f06c0a343721ec0c21943e311a.37
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.39	00000018 .Lanon.9efeb2f06c0a343721ec0c21943e311a.39
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.4	0000000d .Lanon.9efeb2f06c0a343721ec0c21943e311a.4
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.40	00000018 .Lanon.9efeb2f06c0a343721ec0c21943e311a.40
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.41	0000004b .Lanon.9efeb2f06c0a343721ec0c21943e311a.41
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.42	00000018 .Lanon.9efeb2f06c0a343721ec0c21943e311a.42
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.43	00000018 .Lanon.9efeb2f06c0a343721ec0c21943e311a.43
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.44	00000021 .Lanon.9efeb2f06c0a343721ec0c21943e311a.44
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.45	00000012 .Lanon.9efeb2f06c0a343721ec0c21943e311a.45
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.46	00000009 .Lanon.9efeb2f06c0a343721ec0c21943e311a.46
00000008 l     O .rodata.cst8	00000008 .Lanon.9efeb2f06c0a343721ec0c21943e311a.47
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.48	00000001 .Lanon.9efeb2f06c0a343721ec0c21943e311a.48
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.49	0000000c .Lanon.9efeb2f06c0a343721ec0c21943e311a.49
00000000 l     O .rodata.cst4	00000004 .Lanon.9efeb2f06c0a343721ec0c21943e311a.5
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.50	00000009 .Lanon.9efeb2f06c0a343721ec0c21943e311a.50
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.51	0000000d .Lanon.9efeb2f06c0a343721ec0c21943e311a.51
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.52	0000000c .Lanon.9efeb2f06c0a343721ec0c21943e311a.52
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.53	0000000b .Lanon.9efeb2f06c0a343721ec0c21943e311a.53
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.54	0000000c .Lanon.9efeb2f06c0a343721ec0c21943e311a.54
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.55	0000000a .Lanon.9efeb2f06c0a343721ec0c21943e311a.55
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.56	0000000a .Lanon.9efeb2f06c0a343721ec0c21943e311a.56
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.57	00000009 .Lanon.9efeb2f06c0a343721ec0c21943e311a.57
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.58	0000000a .Lanon.9efeb2f06c0a343721ec0c21943e311a.58
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.59	0000000a .Lanon.9efeb2f06c0a343721ec0c21943e311a.59
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.60	00000007 .Lanon.9efeb2f06c0a343721ec0c21943e311a.60
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.61	0000000a .Lanon.9efeb2f06c0a343721ec0c21943e311a.61
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.62	0000000c .Lanon.9efeb2f06c0a343721ec0c21943e311a.62
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.63	0000000a .Lanon.9efeb2f06c0a343721ec0c21943e311a.63
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.64	0000000a .Lanon.9efeb2f06c0a343721ec0c21943e311a.64
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.65	00000007 .Lanon.9efeb2f06c0a343721ec0c21943e311a.65
00000000 l     O .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.9	00000018 .Lanon.9efeb2f06c0a343721ec0c21943e311a.9
00000000 l     F .text._ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17h13ac8c522a55adacE	0000003a _ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17h13ac8c522a55adacE
00000000 l     F .text._ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17hef1b000013b2e9f1E	0000003a _ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17hef1b000013b2e9f1E
00000000 l     F .text._ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E	00000242 _ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E
00000000 l     O .data._ZN5mylib6mynewt2hw6sensor17LISTENER_INTERNAL17h6f9ae9cad3c79823E	00000018 _ZN5mylib6mynewt2hw6sensor17LISTENER_INTERNAL17h6f9ae9cad3c79823E
00000000 l     F .text._ZN5mylib6mynewt2hw6sensor21null_sensor_data_func17he576af080a279986E	00000004 _ZN5mylib6mynewt2hw6sensor21null_sensor_data_func17he576af080a279986E
00000000 l     O .bss._ZN5mylib9send_coap12NETWORK_TASK17hfe4c85d5a08ad1acE	00000050 _ZN5mylib9send_coap12NETWORK_TASK17hfe4c85d5a08ad1acE
00000000 l     O .bss._ZN5mylib9send_coap16NETWORK_IS_READY17h8eedfcb9fe69a092E.0.0	00000001 _ZN5mylib9send_coap16NETWORK_IS_READY17h8eedfcb9fe69a092E.0.0
00000000 l     F .text._ZN5mylib9send_coap17network_task_func17hd9a1eeab35a857d1E	0000011a _ZN5mylib9send_coap17network_task_func17hd9a1eeab35a857d1E
00000000 l     O .bss._ZN5mylib9send_coap18NETWORK_TASK_STACK17h8b663783da39d672E	00000400 _ZN5mylib9send_coap18NETWORK_TASK_STACK17h8b663783da39d672E
00000000 l     O .rodata.str.3	00000010 str.3
00000000 l    d  .text._ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17h13ac8c522a55adacE	00000000 .text._ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17h13ac8c522a55adacE
00000000 l    d  .text._ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17hef1b000013b2e9f1E	00000000 .text._ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17hef1b000013b2e9f1E
00000000 l    d  .text._ZN86_$LT$mylib..mynewt..encoding..json..json_encoder$u20$as$u20$core..default..Default$GT$7default17h3a86dbb2a8a8164dE	00000000 .text._ZN86_$LT$mylib..mynewt..encoding..json..json_encoder$u20$as$u20$core..default..Default$GT$7default17h3a86dbb2a8a8164dE
00000000 l    d  .text._ZN85_$LT$mylib..mynewt..encoding..json..json_enum_t$u20$as$u20$core..default..Default$GT$7default17hbada56f05cb58551E	00000000 .text._ZN85_$LT$mylib..mynewt..encoding..json..json_enum_t$u20$as$u20$core..default..Default$GT$7default17hbada56f05cb58551E
00000000 l    d  .text._ZN114_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17he12df112c375aa63E	00000000 .text._ZN114_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17he12df112c375aa63E
00000000 l    d  .text._ZN100_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h667ef8f6053cc85dE	00000000 .text._ZN100_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h667ef8f6053cc85dE
00000000 l    d  .text._ZN86_$LT$mylib..mynewt..encoding..json..json_array_t$u20$as$u20$core..default..Default$GT$7default17h9ed2b02adbdc200eE	00000000 .text._ZN86_$LT$mylib..mynewt..encoding..json..json_array_t$u20$as$u20$core..default..Default$GT$7default17h9ed2b02adbdc200eE
00000000 l    d  .text._ZN99_$LT$mylib..mynewt..encoding..json..json_attr_t__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hf95111df9d32b5bcE	00000000 .text._ZN99_$LT$mylib..mynewt..encoding..json..json_attr_t__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hf95111df9d32b5bcE
00000000 l    d  .text._ZN85_$LT$mylib..mynewt..encoding..json..json_attr_t$u20$as$u20$core..default..Default$GT$7default17hf2866f3a6beda229E	00000000 .text._ZN85_$LT$mylib..mynewt..encoding..json..json_attr_t$u20$as$u20$core..default..Default$GT$7default17hf2866f3a6beda229E
00000000 l    d  .text._ZN78_$LT$mylib..mynewt..kernel..os..os_event$u20$as$u20$core..default..Default$GT$7default17ha9c2a22a0aef1179E	00000000 .text._ZN78_$LT$mylib..mynewt..kernel..os..os_event$u20$as$u20$core..default..Default$GT$7default17ha9c2a22a0aef1179E
00000000 l    d  .text._ZN80_$LT$mylib..mynewt..kernel..os..os_callout$u20$as$u20$core..default..Default$GT$7default17h35fb82015c01a0aaE	00000000 .text._ZN80_$LT$mylib..mynewt..kernel..os..os_callout$u20$as$u20$core..default..Default$GT$7default17h35fb82015c01a0aaE
00000000 l    d  .text._ZN79_$LT$mylib..mynewt..kernel..os..hal_timer$u20$as$u20$core..default..Default$GT$7default17h662e239b89e341a8E	00000000 .text._ZN79_$LT$mylib..mynewt..kernel..os..hal_timer$u20$as$u20$core..default..Default$GT$7default17h662e239b89e341a8E
00000000 l    d  .text._ZN76_$LT$mylib..mynewt..kernel..os..os_dev$u20$as$u20$core..default..Default$GT$7default17h6796a90f25049da8E	00000000 .text._ZN76_$LT$mylib..mynewt..kernel..os..os_dev$u20$as$u20$core..default..Default$GT$7default17h6796a90f25049da8E
00000000 l    d  .text._ZN77_$LT$mylib..mynewt..kernel..os..os_mbuf$u20$as$u20$core..default..Default$GT$7default17h148a6d1254104847E	00000000 .text._ZN77_$LT$mylib..mynewt..kernel..os..os_mbuf$u20$as$u20$core..default..Default$GT$7default17h148a6d1254104847E
00000000 l    d  .text._ZN80_$LT$mylib..mynewt..kernel..os..os_mempool$u20$as$u20$core..default..Default$GT$7default17ha84ccbb9e7b22964E	00000000 .text._ZN80_$LT$mylib..mynewt..kernel..os..os_mempool$u20$as$u20$core..default..Default$GT$7default17ha84ccbb9e7b22964E
00000000 l    d  .text._ZN85_$LT$mylib..mynewt..kernel..os..os_sanity_check$u20$as$u20$core..default..Default$GT$7default17hd1233b47a9d8cbcbE	00000000 .text._ZN85_$LT$mylib..mynewt..kernel..os..os_sanity_check$u20$as$u20$core..default..Default$GT$7default17hd1233b47a9d8cbcbE
00000000 l    d  .text._ZN77_$LT$mylib..mynewt..kernel..os..os_task$u20$as$u20$core..default..Default$GT$7default17hbcc6978df783f1d8E	00000000 .text._ZN77_$LT$mylib..mynewt..kernel..os..os_task$u20$as$u20$core..default..Default$GT$7default17hbcc6978df783f1d8E
00000000 l    d  .text._ZN76_$LT$mylib..mynewt..kernel..os..os_sem$u20$as$u20$core..default..Default$GT$7default17h5c8e87c2628b6e14E	00000000 .text._ZN76_$LT$mylib..mynewt..kernel..os..os_sem$u20$as$u20$core..default..Default$GT$7default17h5c8e87c2628b6e14E
00000000 l    d  .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000000 .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE
00000000 l    d  .text._ZN93_$LT$mylib..mynewt..hw..sensor..bindings..sensor_data_t$u20$as$u20$core..default..Default$GT$7default17hb4bfaef90e32f038E	00000000 .text._ZN93_$LT$mylib..mynewt..hw..sensor..bindings..sensor_data_t$u20$as$u20$core..default..Default$GT$7default17hb4bfaef90e32f038E
00000000 l    d  .text._ZN95_$LT$mylib..mynewt..hw..sensor..bindings..sensor_listener$u20$as$u20$core..default..Default$GT$7default17h1dd4f66caf63ca67E	00000000 .text._ZN95_$LT$mylib..mynewt..hw..sensor..bindings..sensor_listener$u20$as$u20$core..default..Default$GT$7default17h1dd4f66caf63ca67E
00000000 l    d  .text._ZN98_$LT$mylib..mynewt..hw..sensor..bindings..sensor_type_traits$u20$as$u20$core..default..Default$GT$7default17h604a349a45bc2964E	00000000 .text._ZN98_$LT$mylib..mynewt..hw..sensor..bindings..sensor_type_traits$u20$as$u20$core..default..Default$GT$7default17h604a349a45bc2964E
00000000 l    d  .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_ev_ctx$u20$as$u20$core..default..Default$GT$7default17ha4b50f23ab08f5e7E	00000000 .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_ev_ctx$u20$as$u20$core..default..Default$GT$7default17ha4b50f23ab08f5e7E
00000000 l    d  .text._ZN86_$LT$mylib..mynewt..hw..sensor..bindings..sensor$u20$as$u20$core..default..Default$GT$7default17h3972b4100904ce9dE	00000000 .text._ZN86_$LT$mylib..mynewt..hw..sensor..bindings..sensor$u20$as$u20$core..default..Default$GT$7default17h3972b4100904ce9dE
00000000 l    d  .text._ZN93_$LT$mylib..mynewt..hw..sensor..bindings.._bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hfe61a3a2e7f05b3cE	00000000 .text._ZN93_$LT$mylib..mynewt..hw..sensor..bindings.._bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hfe61a3a2e7f05b3cE
00000000 l    d  .text._ZN5mylib6mynewt2hw6sensor21null_sensor_data_func17he576af080a279986E	00000000 .text._ZN5mylib6mynewt2hw6sensor21null_sensor_data_func17he576af080a279986E
00000000 l    d  .text._ZN101_$LT$mylib..mynewt..libs..sensor_coap..json_value__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h7186c454935d415bE	00000000 .text._ZN101_$LT$mylib..mynewt..libs..sensor_coap..json_value__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h7186c454935d415bE
00000000 l    d  .text._ZN104_$LT$mylib..mynewt..libs..sensor_network..sensor_network_interface$u20$as$u20$core..default..Default$GT$7default17h35426a326eb363b6E	00000000 .text._ZN104_$LT$mylib..mynewt..libs..sensor_network..sensor_network_interface$u20$as$u20$core..default..Default$GT$7default17h35426a326eb363b6E
00000000 l    d  .text._ZN5mylib6mynewt6result95_$LT$impl$u20$core..convert..From$LT$mylib..mynewt..result..MynewtError$GT$$u20$for$u20$i32$GT$4from17he768babb092a5c90E	00000000 .text._ZN5mylib6mynewt6result95_$LT$impl$u20$core..convert..From$LT$mylib..mynewt..result..MynewtError$GT$$u20$for$u20$i32$GT$4from17he768babb092a5c90E
00000000 l    d  .text._ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E	00000000 .text._ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E
00000000 l    d  .text._ZN5mylib9send_coap17network_task_func17hd9a1eeab35a857d1E	00000000 .text._ZN5mylib9send_coap17network_task_func17hd9a1eeab35a857d1E
00000000 l    d  .text.main	00000000 .text.main
00000000 l    d  .text.rust_begin_unwind	00000000 .text.rust_begin_unwind
00000000 l    d  .text._ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE	00000000 .text._ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE
00000000 l    d  .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.0	00000000 .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.0
00000000 l    d  .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.1	00000000 .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.1
00000000 l    d  .data._ZN5mylib6mynewt2hw6sensor17LISTENER_INTERNAL17h6f9ae9cad3c79823E	00000000 .data._ZN5mylib6mynewt2hw6sensor17LISTENER_INTERNAL17h6f9ae9cad3c79823E
00000000 l    d  .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.6	00000000 .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.6
00000000 l    d  .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.7	00000000 .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.7
00000000 l    d  .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.8	00000000 .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.8
00000000 l    d  .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.10	00000000 .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.10
00000000 l    d  .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.12	00000000 .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.12
00000000 l    d  .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.16	00000000 .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.16
00000000 l    d  .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.19	00000000 .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.19
00000000 l    d  .bss._ZN5mylib9send_coap12NETWORK_TASK17hfe4c85d5a08ad1acE	00000000 .bss._ZN5mylib9send_coap12NETWORK_TASK17hfe4c85d5a08ad1acE
00000000 l    d  .bss._ZN5mylib9send_coap18NETWORK_TASK_STACK17h8b663783da39d672E	00000000 .bss._ZN5mylib9send_coap18NETWORK_TASK_STACK17h8b663783da39d672E
00000000 l    d  .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.27	00000000 .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.27
00000000 l    d  .rodata.str.3	00000000 .rodata.str.3
00000000 l    d  .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.35	00000000 .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.35
00000000 l    d  .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.38	00000000 .rodata..Lanon.9efeb2f06c0a343721ec0c21943e311a.38
00000000 l    d  .bss._ZN5mylib9send_coap16NETWORK_IS_READY17h8eedfcb9fe69a092E.0.0	00000000 .bss._ZN5mylib9send_coap16NETWORK_IS_READY17h8eedfcb9fe69a092E.0.0
00000000 l    d  .debug_loc	00000000 .debug_loc
00000000 l    d  .debug_abbrev	00000000 .debug_abbrev
00000000 l    d  .debug_info	00000000 .debug_info
00000000 l    d  .debug_ranges	00000000 .debug_ranges
00000000 l    d  .debug_frame	00000000 .debug_frame
00000000 l    d  .debug_line	00000000 .debug_line
00000000 g     F .text._ZN100_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h667ef8f6053cc85dE	00000010 _ZN100_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h667ef8f6053cc85dE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h2aaf975749bb6b1cE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor__bindgen_ty_2$u20$as$u20$core..default..Default$GT$7default17hc8dd8eb7cdbfe98cE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor__bindgen_ty_3$u20$as$u20$core..default..Default$GT$7default17h309f01b3610ccf17E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor__bindgen_ty_4$u20$as$u20$core..default..Default$GT$7default17hcc1172401ad6a71eE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_ev_ctx$u20$as$u20$core..default..Default$GT$7default17ha4b50f23ab08f5e7E	00000006 _ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_ev_ctx$u20$as$u20$core..default..Default$GT$7default17ha4b50f23ab08f5e7E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN101_$LT$mylib..mynewt..hw..sensor..bindings..os_task__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h7fd217d74324c71eE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_ev_ctx$u20$as$u20$core..default..Default$GT$7default17ha4b50f23ab08f5e7E	00000006 _ZN101_$LT$mylib..mynewt..hw..sensor..bindings..os_task__bindgen_ty_2$u20$as$u20$core..default..Default$GT$7default17haf7ba7d2a200f199E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN101_$LT$mylib..mynewt..hw..sensor..bindings..os_task__bindgen_ty_3$u20$as$u20$core..default..Default$GT$7default17h6d9a4af3b8df63d2E
00000000 g     F .text._ZN101_$LT$mylib..mynewt..libs..sensor_coap..json_value__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h7186c454935d415bE	0000000c _ZN101_$LT$mylib..mynewt..libs..sensor_coap..json_value__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h7186c454935d415bE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN101_$LT$mylib..mynewt..libs..sensor_coap..os_mempool__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17he276f62175cd5300E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN101_$LT$mylib..mynewt..libs..sensor_coap..os_mempool__bindgen_ty_2$u20$as$u20$core..default..Default$GT$7default17h1f234c804e40a8f1E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN102_$LT$mylib..mynewt..hw..sensor..bindings..os_event__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h4ea54df93f92a8bcE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN102_$LT$mylib..mynewt..hw..sensor..bindings..os_mutex__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h36afc34b5137132aE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN102_$LT$mylib..mynewt..libs..sensor_coap..os_memblock__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hf1df87288a25ef5dE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_ev_ctx$u20$as$u20$core..default..Default$GT$7default17ha4b50f23ab08f5e7E	00000006 _ZN103_$LT$mylib..mynewt..hw..sensor..bindings..os_eventq__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hb44f7a2daa7ca2aaE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN103_$LT$mylib..mynewt..libs..sensor_coap..os_mbuf_pool__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h37ac2b0e576fa38dE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_ev_ctx$u20$as$u20$core..default..Default$GT$7default17ha4b50f23ab08f5e7E	00000006 _ZN104_$LT$mylib..mynewt..hw..sensor..bindings..os_callout__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h697cbb2d3a6c6d61E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN104_$LT$mylib..mynewt..hw..sensor..bindings..os_mempool__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h3fdcadc250213be1E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN104_$LT$mylib..mynewt..hw..sensor..bindings..os_mempool__bindgen_ty_2$u20$as$u20$core..default..Default$GT$7default17h9eb6d80763c22928E
00000000 g     F .text._ZN104_$LT$mylib..mynewt..libs..sensor_network..sensor_network_interface$u20$as$u20$core..default..Default$GT$7default17h35426a326eb363b6E	0000000e _ZN104_$LT$mylib..mynewt..libs..sensor_network..sensor_network_interface$u20$as$u20$core..default..Default$GT$7default17h35426a326eb363b6E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN105_$LT$mylib..mynewt..hw..sensor..bindings..os_memblock__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h6438b59c17272d3eE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN106_$LT$mylib..mynewt..libs..mynewt_rust..os_sanity_check__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hd5f7ca9ad434557bE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN106_$LT$mylib..mynewt..libs..mynewt_rust..sensor_listener__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hd5977ba5b30fb899E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN106_$LT$mylib..mynewt..libs..mynewt_rust..sensor_notifier__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hade3ec4b47e8a902E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN107_$LT$mylib..mynewt..hw..sensor..bindings.._bindgen_ty_1__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h843d7969e879e569E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN107_$LT$mylib..mynewt..kernel..os..os_time_change_listener__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17he24935c7ac6204cdE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN109_$LT$mylib..mynewt..hw..sensor..bindings..os_sanity_check__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h0feaa15ed59bdca0E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN109_$LT$mylib..mynewt..hw..sensor..bindings..sensor_listener__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h8ff115dd6a1fc458E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN109_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notifier__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h637ccd41ee238bb5E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN109_$LT$mylib..mynewt..libs..mynewt_rust..sensor_type_traits__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h3219e485f2732957E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_ev_ctx$u20$as$u20$core..default..Default$GT$7default17ha4b50f23ab08f5e7E	00000006 _ZN112_$LT$mylib..mynewt..encoding..json..json_value__bindgen_ty_1__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hf3a6f726d3914f17E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN112_$LT$mylib..mynewt..hw..sensor..bindings..sensor_type_traits__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hf7b7aaa7d82fe4e0E
00000000 g     F .text._ZN114_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17he12df112c375aa63E	0000000a _ZN114_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17he12df112c375aa63E
00000000 g     F .text._ZN114_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17he12df112c375aa63E	0000000a _ZN114_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1__bindgen_ty_2$u20$as$u20$core..default..Default$GT$7default17h60e4be6e84f5f5e0E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN114_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1__bindgen_ty_3$u20$as$u20$core..default..Default$GT$7default17h4464eba725c38e01E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN114_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1__bindgen_ty_4$u20$as$u20$core..default..Default$GT$7default17ha73cde4bf76a0e98E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN114_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1__bindgen_ty_5$u20$as$u20$core..default..Default$GT$7default17h8ac35a0553f64693E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN114_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1__bindgen_ty_6$u20$as$u20$core..default..Default$GT$7default17h0ff45419416194b5E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_ev_ctx$u20$as$u20$core..default..Default$GT$7default17ha4b50f23ab08f5e7E	00000006 _ZN115_$LT$mylib..mynewt..libs..sensor_coap..json_value__bindgen_ty_1__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h6f9864e8b278f2d7E
00000000         *UND*	00000000 _ZN4core3fmt3num3imp51_$LT$impl$u20$core..fmt..Display$u20$for$u20$u8$GT$3fmt17heb4d046d241d78d0E
00000000         *UND*	00000000 _ZN4core3fmt3num3imp52_$LT$impl$u20$core..fmt..Display$u20$for$u20$i32$GT$3fmt17h33b3bbdbc74b88baE
00000000         *UND*	00000000 _ZN4core3fmt3num52_$LT$impl$u20$core..fmt..LowerHex$u20$for$u20$u8$GT$3fmt17he275dc913fe9b8e5E
00000000         *UND*	00000000 _ZN4core3fmt3num52_$LT$impl$u20$core..fmt..UpperHex$u20$for$u20$u8$GT$3fmt17h1d24bfddebe6efa8E
00000000         *UND*	00000000 _ZN4core3fmt3num53_$LT$impl$u20$core..fmt..LowerHex$u20$for$u20$i32$GT$3fmt17hb2119167a92723afE
00000000         *UND*	00000000 _ZN4core3fmt3num53_$LT$impl$u20$core..fmt..UpperHex$u20$for$u20$i32$GT$3fmt17hc44988ae29d24532E
00000000         *UND*	00000000 _ZN4core3fmt8builders10DebugTuple6finish17h24d91625b3672e6dE
00000000         *UND*	00000000 _ZN4core3fmt9Formatter11debug_tuple17h793087e8ecab9022E
00000000         *UND*	00000000 _ZN4core3fmt9Formatter15debug_lower_hex17h6ead2f28bb05b574E
00000000         *UND*	00000000 _ZN4core3fmt9Formatter15debug_upper_hex17hd6d96e6aa5cb78d8E
00000000         *UND*	00000000 _ZN4core5panic8Location4file17h94cc6af18de736c4E
00000000         *UND*	00000000 _ZN4core5panic8Location4line17h3ffc63f14d0a6636E
00000000         *UND*	00000000 _ZN4core5panic9PanicInfo8location17h5226165d8771f8a2E
00000000         *UND*	00000000 _ZN4core5slice20slice_index_len_fail17hedb5bb240677a6b7E
00000000         *UND*	00000000 _ZN4core9panicking18panic_bounds_check17h946762cd0671aec9E
00000000         *UND*	00000000 _ZN4core9panicking5panic17h53ca63c6ac6312f8E
00000000         *UND*	00000000 _ZN4core9panicking9panic_fmt17h6b4d8e87b0965449E
00000000 g     F .text._ZN5mylib6mynewt6result95_$LT$impl$u20$core..convert..From$LT$mylib..mynewt..result..MynewtError$GT$$u20$for$u20$i32$GT$4from17he768babb092a5c90E	00000002 _ZN5mylib6mynewt6result95_$LT$impl$u20$core..convert..From$LT$mylib..mynewt..result..MynewtError$GT$$u20$for$u20$i32$GT$4from17he768babb092a5c90E
00000000 g     F .text._ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE	0000011a _ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE
00000000 g     F .text._ZN76_$LT$mylib..mynewt..kernel..os..os_dev$u20$as$u20$core..default..Default$GT$7default17h6796a90f25049da8E	0000000a _ZN76_$LT$mylib..mynewt..kernel..os..os_dev$u20$as$u20$core..default..Default$GT$7default17h6796a90f25049da8E
00000000 g     F .text._ZN76_$LT$mylib..mynewt..kernel..os..os_sem$u20$as$u20$core..default..Default$GT$7default17h5c8e87c2628b6e14E	00000008 _ZN76_$LT$mylib..mynewt..kernel..os..os_sem$u20$as$u20$core..default..Default$GT$7default17h5c8e87c2628b6e14E
00000000 g     F .text._ZN77_$LT$mylib..mynewt..kernel..os..os_mbuf$u20$as$u20$core..default..Default$GT$7default17h148a6d1254104847E	0000000c _ZN77_$LT$mylib..mynewt..kernel..os..os_mbuf$u20$as$u20$core..default..Default$GT$7default17h148a6d1254104847E
00000000 g     F .text._ZN77_$LT$mylib..mynewt..kernel..os..os_task$u20$as$u20$core..default..Default$GT$7default17hbcc6978df783f1d8E	0000000a _ZN77_$LT$mylib..mynewt..kernel..os..os_task$u20$as$u20$core..default..Default$GT$7default17hbcc6978df783f1d8E
00000000 g     F .text._ZN78_$LT$mylib..mynewt..kernel..os..os_event$u20$as$u20$core..default..Default$GT$7default17ha9c2a22a0aef1179E	0000000c _ZN78_$LT$mylib..mynewt..kernel..os..os_event$u20$as$u20$core..default..Default$GT$7default17ha9c2a22a0aef1179E
00000000 g     F .text._ZN114_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17he12df112c375aa63E	0000000a _ZN78_$LT$mylib..mynewt..kernel..os..os_mutex$u20$as$u20$core..default..Default$GT$7default17he9bfb3f094d874e2E
00000000 g     F .text._ZN79_$LT$mylib..mynewt..kernel..os..hal_timer$u20$as$u20$core..default..Default$GT$7default17h662e239b89e341a8E	00000010 _ZN79_$LT$mylib..mynewt..kernel..os..hal_timer$u20$as$u20$core..default..Default$GT$7default17h662e239b89e341a8E
00000000 g     F .text._ZN77_$LT$mylib..mynewt..kernel..os..os_mbuf$u20$as$u20$core..default..Default$GT$7default17h148a6d1254104847E	0000000c _ZN79_$LT$mylib..mynewt..kernel..os..os_eventq$u20$as$u20$core..default..Default$GT$7default17hf81f4c4eed0fea01E
00000000 g     F .text._ZN79_$LT$mylib..mynewt..kernel..os..hal_timer$u20$as$u20$core..default..Default$GT$7default17h662e239b89e341a8E	00000010 _ZN79_$LT$mylib..mynewt..kernel..os..os_mqueue$u20$as$u20$core..default..Default$GT$7default17he1eabfd3c9c5059aE
00000000 g     F .text._ZN80_$LT$mylib..mynewt..kernel..os..os_callout$u20$as$u20$core..default..Default$GT$7default17h35fb82015c01a0aaE	00000014 _ZN80_$LT$mylib..mynewt..kernel..os..os_callout$u20$as$u20$core..default..Default$GT$7default17h35fb82015c01a0aaE
00000000 g     F .text._ZN80_$LT$mylib..mynewt..kernel..os..os_mempool$u20$as$u20$core..default..Default$GT$7default17ha84ccbb9e7b22964E	00000012 _ZN80_$LT$mylib..mynewt..kernel..os..os_mempool$u20$as$u20$core..default..Default$GT$7default17ha84ccbb9e7b22964E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN81_$LT$mylib..mynewt..kernel..os..os_memblock$u20$as$u20$core..default..Default$GT$7default17hb70e2a35404ff3f5E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN81_$LT$mylib..mynewt..kernel..os..os_task_obj$u20$as$u20$core..default..Default$GT$7default17hd267e38b78964cd7E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN82_$LT$mylib..mynewt..encoding..tinycbor..File$u20$as$u20$core..default..Default$GT$7default17h16d8f5c8d73d8ce8E
00000000 g     F .text._ZN114_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17he12df112c375aa63E	0000000a _ZN82_$LT$mylib..mynewt..kernel..os..os_mbuf_pool$u20$as$u20$core..default..Default$GT$7default17hfc631c771b8ad3d8E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_ev_ctx$u20$as$u20$core..default..Default$GT$7default17ha4b50f23ab08f5e7E	00000006 _ZN82_$LT$mylib..mynewt..kernel..os..os_task_list$u20$as$u20$core..default..Default$GT$7default17h6ad5d1325c893b21E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h667ef8f6053cc85dE	00000010 _ZN84_$LT$mylib..mynewt..encoding..json..json_value$u20$as$u20$core..default..Default$GT$7default17ha918853d3f93dfabE
00000000 g     F .text._ZN76_$LT$mylib..mynewt..kernel..os..os_sem$u20$as$u20$core..default..Default$GT$7default17h5c8e87c2628b6e14E	00000008 _ZN84_$LT$mylib..mynewt..kernel..os..os_mbuf_pkthdr$u20$as$u20$core..default..Default$GT$7default17h14615e02ac7e02e2E
00000000 g     F .text._ZN76_$LT$mylib..mynewt..kernel..os..os_dev$u20$as$u20$core..default..Default$GT$7default17h6796a90f25049da8E	0000000a _ZN84_$LT$mylib..mynewt..kernel..os..os_mempool_ext$u20$as$u20$core..default..Default$GT$7default17hbb33359422b0355dE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_ev_ctx$u20$as$u20$core..default..Default$GT$7default17ha4b50f23ab08f5e7E	00000006 _ZN84_$LT$mylib..mynewt..kernel..os..os_task_stailq$u20$as$u20$core..default..Default$GT$7default17hd395c6bb0accfa03E
00000000 g     F .text._ZN77_$LT$mylib..mynewt..kernel..os..os_mbuf$u20$as$u20$core..default..Default$GT$7default17h148a6d1254104847E	0000000c _ZN84_$LT$mylib..mynewt..libs..sensor_coap..os_mbuf$u20$as$u20$core..default..Default$GT$7default17h920a76fadc95fe44E
00000000 g     F .text._ZN85_$LT$mylib..mynewt..encoding..json..json_attr_t$u20$as$u20$core..default..Default$GT$7default17hf2866f3a6beda229E	0000000a _ZN85_$LT$mylib..mynewt..encoding..json..json_attr_t$u20$as$u20$core..default..Default$GT$7default17hf2866f3a6beda229E
00000000 g     F .text._ZN85_$LT$mylib..mynewt..encoding..json..json_enum_t$u20$as$u20$core..default..Default$GT$7default17hbada56f05cb58551E	00000008 _ZN85_$LT$mylib..mynewt..encoding..json..json_enum_t$u20$as$u20$core..default..Default$GT$7default17hbada56f05cb58551E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_ev_ctx$u20$as$u20$core..default..Default$GT$7default17ha4b50f23ab08f5e7E	00000006 _ZN85_$LT$mylib..mynewt..kernel..os..os_callout_list$u20$as$u20$core..default..Default$GT$7default17hacb08dfb9d315f7dE
00000000 g     F .text._ZN85_$LT$mylib..mynewt..kernel..os..os_sanity_check$u20$as$u20$core..default..Default$GT$7default17hd1233b47a9d8cbcbE	0000000e _ZN85_$LT$mylib..mynewt..kernel..os..os_sanity_check$u20$as$u20$core..default..Default$GT$7default17hd1233b47a9d8cbcbE
00000000 g     F .text._ZN5mylib6mynewt6result95_$LT$impl$u20$core..convert..From$LT$mylib..mynewt..result..MynewtError$GT$$u20$for$u20$i32$GT$4from17he768babb092a5c90E	00000002 _ZN85_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..convert..From$LT$i32$GT$$GT$4from17hf5bfcb9663d3a482E
00000000 g     F .text._ZN86_$LT$mylib..mynewt..encoding..json..json_array_t$u20$as$u20$core..default..Default$GT$7default17h9ed2b02adbdc200eE	0000000a _ZN86_$LT$mylib..mynewt..encoding..json..json_array_t$u20$as$u20$core..default..Default$GT$7default17h9ed2b02adbdc200eE
00000000 g     F .text._ZN86_$LT$mylib..mynewt..encoding..json..json_encoder$u20$as$u20$core..default..Default$GT$7default17h3a86dbb2a8a8164dE	0000000a _ZN86_$LT$mylib..mynewt..encoding..json..json_encoder$u20$as$u20$core..default..Default$GT$7default17h3a86dbb2a8a8164dE
00000000 g     F .text._ZN86_$LT$mylib..mynewt..hw..sensor..bindings..sensor$u20$as$u20$core..default..Default$GT$7default17h3972b4100904ce9dE	0000000a _ZN86_$LT$mylib..mynewt..hw..sensor..bindings..sensor$u20$as$u20$core..default..Default$GT$7default17h3972b4100904ce9dE
00000000 g     F .text._ZN77_$LT$mylib..mynewt..kernel..os..os_mbuf$u20$as$u20$core..default..Default$GT$7default17h148a6d1254104847E	0000000c _ZN87_$LT$mylib..mynewt..encoding..tinycbor..CborValue$u20$as$u20$core..default..Default$GT$7default17h1de8a44b98a2196dE
00000000 g     F .text._ZN80_$LT$mylib..mynewt..kernel..os..os_mempool$u20$as$u20$core..default..Default$GT$7default17ha84ccbb9e7b22964E	00000012 _ZN87_$LT$mylib..mynewt..libs..sensor_coap..os_mempool$u20$as$u20$core..default..Default$GT$7default17h4ddbf27b97b6cad4E
00000000 g     F .text._ZN114_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17he12df112c375aa63E	0000000a _ZN88_$LT$mylib..mynewt..encoding..tinycbor..CborParser$u20$as$u20$core..default..Default$GT$7default17h0a3e703f11c9ffa7E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_ev_ctx$u20$as$u20$core..default..Default$GT$7default17ha4b50f23ab08f5e7E	00000006 _ZN88_$LT$mylib..mynewt..encoding..tinycbor..cbor_iovec$u20$as$u20$core..default..Default$GT$7default17h9ab3be1ec0c1a307E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN88_$LT$mylib..mynewt..libs..sensor_coap..os_memblock$u20$as$u20$core..default..Default$GT$7default17h2d7672e8f0281133E
00000000 g     F .text._ZN77_$LT$mylib..mynewt..kernel..os..os_mbuf$u20$as$u20$core..default..Default$GT$7default17h148a6d1254104847E	0000000c _ZN89_$LT$mylib..mynewt..encoding..tinycbor..CborEncoder$u20$as$u20$core..default..Default$GT$7default17h3730d6a3b7b87eb0E
00000000 g     F .text._ZN85_$LT$mylib..mynewt..kernel..os..os_sanity_check$u20$as$u20$core..default..Default$GT$7default17hd1233b47a9d8cbcbE	0000000e _ZN89_$LT$mylib..mynewt..kernel..os..os_time_change_info$u20$as$u20$core..default..Default$GT$7default17h8cb3ceeea00d7257E
00000000 g     F .text._ZN114_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17he12df112c375aa63E	0000000a _ZN89_$LT$mylib..mynewt..libs..sensor_coap..os_mbuf_pool$u20$as$u20$core..default..Default$GT$7default17h04df727234d68cd1E
00000000 g     F .text._ZN77_$LT$mylib..mynewt..kernel..os..os_mbuf$u20$as$u20$core..default..Default$GT$7default17h148a6d1254104847E	0000000c _ZN89_$LT$mylib..mynewt..libs..sensor_coap..sensor_value$u20$as$u20$core..default..Default$GT$7default17h1f6a572a97868ffbE
00000000 g     F .text._ZN104_$LT$mylib..mynewt..libs..sensor_network..sensor_network_interface$u20$as$u20$core..default..Default$GT$7default17h35426a326eb363b6E	0000000e _ZN90_$LT$mylib..mynewt..hw..sensor..bindings..sensor_itf$u20$as$u20$core..default..Default$GT$7default17h1891655938f1272dE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN90_$LT$mylib..mynewt..kernel..os..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h429eb1b811f46821E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN90_$LT$mylib..mynewt..kernel..os..os_sem__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17ha8b09db2daae9898E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN91_$LT$mylib..mynewt..kernel..os..os_mbuf__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hb357509788236681E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN91_$LT$mylib..mynewt..kernel..os..os_task__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h118441e24fe64a9eE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_ev_ctx$u20$as$u20$core..default..Default$GT$7default17ha4b50f23ab08f5e7E	00000006 _ZN91_$LT$mylib..mynewt..kernel..os..os_task__bindgen_ty_2$u20$as$u20$core..default..Default$GT$7default17haefc6aae40627d37E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN91_$LT$mylib..mynewt..kernel..os..os_task__bindgen_ty_3$u20$as$u20$core..default..Default$GT$7default17hf2f940fdf2e440ebE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN92_$LT$mylib..mynewt..kernel..os..os_event__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hd029ecee171aa65aE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN92_$LT$mylib..mynewt..kernel..os..os_mutex__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h27d68578cc3c9303E
00000000 g     F .text._ZN93_$LT$mylib..mynewt..hw..sensor..bindings.._bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hfe61a3a2e7f05b3cE	0000000a _ZN93_$LT$mylib..mynewt..hw..sensor..bindings.._bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hfe61a3a2e7f05b3cE
00000000 g     F .text._ZN93_$LT$mylib..mynewt..hw..sensor..bindings..sensor_data_t$u20$as$u20$core..default..Default$GT$7default17hb4bfaef90e32f038E	00000008 _ZN93_$LT$mylib..mynewt..hw..sensor..bindings..sensor_data_t$u20$as$u20$core..default..Default$GT$7default17hb4bfaef90e32f038E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_ev_ctx$u20$as$u20$core..default..Default$GT$7default17ha4b50f23ab08f5e7E	00000006 _ZN93_$LT$mylib..mynewt..kernel..os..hal_timer__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hf2a3da75438eb086E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_ev_ctx$u20$as$u20$core..default..Default$GT$7default17ha4b50f23ab08f5e7E	00000006 _ZN93_$LT$mylib..mynewt..kernel..os..os_eventq__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h99c4e5d1fae27bd7E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_ev_ctx$u20$as$u20$core..default..Default$GT$7default17ha4b50f23ab08f5e7E	00000006 _ZN93_$LT$mylib..mynewt..kernel..os..os_mqueue__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hc2410fc13011d655E
00000000 g     F .text._ZN114_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17he12df112c375aa63E	0000000a _ZN93_$LT$mylib..mynewt..kernel..os..os_time_change_listener$u20$as$u20$core..default..Default$GT$7default17h4c1956f8845f6eeeE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_ev_ctx$u20$as$u20$core..default..Default$GT$7default17ha4b50f23ab08f5e7E	00000006 _ZN94_$LT$mylib..mynewt..kernel..os..os_callout__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h3197e8ecd45933d4E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN94_$LT$mylib..mynewt..kernel..os..os_mempool__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h30d40da8a7ebee30E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN94_$LT$mylib..mynewt..kernel..os..os_mempool__bindgen_ty_2$u20$as$u20$core..default..Default$GT$7default17h8f0e04c0414de32dE
00000000 g     F .text._ZN95_$LT$mylib..mynewt..hw..sensor..bindings..sensor_listener$u20$as$u20$core..default..Default$GT$7default17h1dd4f66caf63ca67E	00000010 _ZN95_$LT$mylib..mynewt..hw..sensor..bindings..sensor_listener$u20$as$u20$core..default..Default$GT$7default17h1dd4f66caf63ca67E
00000000 g     F .text._ZN77_$LT$mylib..mynewt..kernel..os..os_mbuf$u20$as$u20$core..default..Default$GT$7default17h148a6d1254104847E	0000000c _ZN95_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notifier$u20$as$u20$core..default..Default$GT$7default17h5316c0c3bcdcca59E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_ev_ctx$u20$as$u20$core..default..Default$GT$7default17ha4b50f23ab08f5e7E	00000006 _ZN95_$LT$mylib..mynewt..hw..sensor..bindings..sensor_read_ctx$u20$as$u20$core..default..Default$GT$7default17h33401c6a27569b04E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN95_$LT$mylib..mynewt..kernel..os..os_memblock__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hf0f04af4e71230cbE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN95_$LT$mylib..mynewt..kernel..os..os_task_obj__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h27bc7fbe06e15e40E
00000000 g     F .text._ZN95_$LT$mylib..mynewt..hw..sensor..bindings..sensor_listener$u20$as$u20$core..default..Default$GT$7default17h1dd4f66caf63ca67E	00000010 _ZN96_$LT$mylib..mynewt..hw..sensor..bindings..sensor_timestamp$u20$as$u20$core..default..Default$GT$7default17h6c09419f817bfc18E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN96_$LT$mylib..mynewt..kernel..os..os_mbuf_pool__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h562e492392a30d0aE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN97_$LT$mylib..mynewt..libs..mynewt_rust..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hdb498e4f06b338a2E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN97_$LT$mylib..mynewt..libs..mynewt_rust..sensor__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hb36d57d384a9e5bdE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN97_$LT$mylib..mynewt..libs..mynewt_rust..sensor__bindgen_ty_2$u20$as$u20$core..default..Default$GT$7default17hb7c0e73ce4cce040E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN97_$LT$mylib..mynewt..libs..mynewt_rust..sensor__bindgen_ty_3$u20$as$u20$core..default..Default$GT$7default17h34ee4452fed8a02dE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN97_$LT$mylib..mynewt..libs..mynewt_rust..sensor__bindgen_ty_4$u20$as$u20$core..default..Default$GT$7default17h503060d86208d3f4E
00000000 g     F .text._ZN101_$LT$mylib..mynewt..libs..sensor_coap..json_value__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h7186c454935d415bE	0000000c _ZN98_$LT$mylib..mynewt..encoding..json..json_value__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hb4d0a1ab475c3667E
00000000 g     F .text._ZN85_$LT$mylib..mynewt..encoding..json..json_enum_t$u20$as$u20$core..default..Default$GT$7default17hbada56f05cb58551E	00000008 _ZN98_$LT$mylib..mynewt..hw..sensor..bindings..sensor_read_ev_ctx$u20$as$u20$core..default..Default$GT$7default17h584b56ab500a71f7E
00000000 g     F .text._ZN98_$LT$mylib..mynewt..hw..sensor..bindings..sensor_type_traits$u20$as$u20$core..default..Default$GT$7default17h604a349a45bc2964E	0000000a _ZN98_$LT$mylib..mynewt..hw..sensor..bindings..sensor_type_traits$u20$as$u20$core..default..Default$GT$7default17h604a349a45bc2964E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN98_$LT$mylib..mynewt..kernel..os..os_mbuf_pkthdr__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17haa3ffeaf3c07db34E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN98_$LT$mylib..mynewt..libs..mynewt_rust..os_task__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h71178c47107c685bE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_ev_ctx$u20$as$u20$core..default..Default$GT$7default17ha4b50f23ab08f5e7E	00000006 _ZN98_$LT$mylib..mynewt..libs..mynewt_rust..os_task__bindgen_ty_2$u20$as$u20$core..default..Default$GT$7default17h2bf9b06fce62f76dE
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN98_$LT$mylib..mynewt..libs..mynewt_rust..os_task__bindgen_ty_3$u20$as$u20$core..default..Default$GT$7default17ha9927272e3838b42E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN98_$LT$mylib..mynewt..libs..sensor_coap..os_mbuf__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h8f8ce82b661a48d2E
00000000 g     F .text._ZN99_$LT$mylib..mynewt..encoding..json..json_attr_t__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hf95111df9d32b5bcE	0000000a _ZN99_$LT$mylib..mynewt..encoding..json..json_attr_t__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hf95111df9d32b5bcE
00000000 g     F .text._ZN93_$LT$mylib..mynewt..hw..sensor..bindings..sensor_data_t$u20$as$u20$core..default..Default$GT$7default17hb4bfaef90e32f038E	00000008 _ZN99_$LT$mylib..mynewt..encoding..json..json_attr_t__bindgen_ty_2$u20$as$u20$core..default..Default$GT$7default17h08bfa0c7f79dd386E
00000000 g     F .text._ZN79_$LT$mylib..mynewt..kernel..os..hal_timer$u20$as$u20$core..default..Default$GT$7default17h662e239b89e341a8E	00000010 _ZN99_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_os_ev$u20$as$u20$core..default..Default$GT$7default17h3a71d73701d9a135E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN99_$LT$mylib..mynewt..kernel..os..os_sanity_check__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h0f02a5038f430112E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN99_$LT$mylib..mynewt..libs..mynewt_rust..os_event__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hc0fb160539bdbe90E
00000000 g     F .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE	00000004 _ZN99_$LT$mylib..mynewt..libs..mynewt_rust..os_mutex__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hce8b6a454723912bE
00000000         *UND*	00000000 _ZN9cstr_core4CStr8from_ptr17h02056df58ddde440E
00000000         *UND*	00000000 __aeabi_memclr4
00000000         *UND*	00000000 __aeabi_memclr8
00000000         *UND*	00000000 __bkpt
00000000         *UND*	00000000 console_buffer
00000000         *UND*	00000000 console_flush
00000000         *UND*	00000000 console_printhex
00000000         *UND*	00000000 device_get_name
00000000         *UND*	00000000 do_collector_post
00000000         *UND*	00000000 do_server_post
00000000         *UND*	00000000 get_device_id
00000000         *UND*	00000000 get_temp_data
00000000         *UND*	00000000 get_temp_raw_data
00000000         *UND*	00000000 init_collector_post
00000000         *UND*	00000000 init_server_post
00000000         *UND*	00000000 is_collector_node
00000000         *UND*	00000000 is_null_sensor
00000000         *UND*	00000000 is_null_sensor_data
00000000         *UND*	00000000 is_sensor_node
00000000         *UND*	00000000 is_standalone_node
00000000 g     F .text.main	00000192 main
00000000         *UND*	00000000 null_sensor
00000000         *UND*	00000000 os_eventq_dflt_get
00000000         *UND*	00000000 os_eventq_run
00000000         *UND*	00000000 os_task_init
00000000         *UND*	00000000 os_time_delay
00000000         *UND*	00000000 register_collector_transport
00000000         *UND*	00000000 register_server_transport
00000000 g     F .text.rust_begin_unwind	00000072 rust_begin_unwind
00000000         *UND*	00000000 rust_sysinit
00000000         *UND*	00000000 sensor_get_device
00000000         *UND*	00000000 sensor_mgr_find_next_bydevname
00000000         *UND*	00000000 sensor_register_listener
00000000         *UND*	00000000 sensor_set_poll_rate_ms
00000000         *UND*	00000000 should_send_to_collector



Disassembly of section .text._ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17h13ac8c522a55adacE:

00000000 <_ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17h13ac8c522a55adacE>:
_ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17h13ac8c522a55adacE():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/fmt/mod.rs:1914
   0:	b5b0      	push	{r4, r5, r7, lr}
   2:	6805      	ldr	r5, [r0, #0]
_ZN4core3fmt3num50_$LT$impl$u20$core..fmt..Debug$u20$for$u20$i32$GT$3fmt17hc0a5c2426ccebe61E():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/fmt/num.rs:147
   4:	4608      	mov	r0, r1
   6:	460c      	mov	r4, r1
   8:	f7ff fffe 	bl	0 <_ZN4core3fmt9Formatter15debug_lower_hex17h6ead2f28bb05b574E>
   c:	b128      	cbz	r0, 1a <_ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17h13ac8c522a55adacE+0x1a>
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/fmt/num.rs:148
   e:	4628      	mov	r0, r5
  10:	4621      	mov	r1, r4
  12:	e8bd 40b0 	ldmia.w	sp!, {r4, r5, r7, lr}
  16:	f7ff bffe 	b.w	0 <_ZN4core3fmt3num53_$LT$impl$u20$core..fmt..LowerHex$u20$for$u20$i32$GT$3fmt17hb2119167a92723afE>
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/fmt/num.rs:149
  1a:	4620      	mov	r0, r4
  1c:	f7ff fffe 	bl	0 <_ZN4core3fmt9Formatter15debug_upper_hex17hd6d96e6aa5cb78d8E>
  20:	b128      	cbz	r0, 2e <_ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17h13ac8c522a55adacE+0x2e>
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/fmt/num.rs:150
  22:	4628      	mov	r0, r5
  24:	4621      	mov	r1, r4
  26:	e8bd 40b0 	ldmia.w	sp!, {r4, r5, r7, lr}
  2a:	f7ff bffe 	b.w	0 <_ZN4core3fmt3num53_$LT$impl$u20$core..fmt..UpperHex$u20$for$u20$i32$GT$3fmt17hc44988ae29d24532E>
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/fmt/num.rs:152
  2e:	4628      	mov	r0, r5
  30:	4621      	mov	r1, r4
  32:	e8bd 40b0 	ldmia.w	sp!, {r4, r5, r7, lr}
  36:	f7ff bffe 	b.w	0 <_ZN4core3fmt3num3imp52_$LT$impl$u20$core..fmt..Display$u20$for$u20$i32$GT$3fmt17h33b3bbdbc74b88baE>

Disassembly of section .text._ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17hef1b000013b2e9f1E:

00000000 <_ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17hef1b000013b2e9f1E>:
_ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17hef1b000013b2e9f1E():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/fmt/mod.rs:1914
   0:	b5b0      	push	{r4, r5, r7, lr}
   2:	6805      	ldr	r5, [r0, #0]
_ZN4core3fmt3num49_$LT$impl$u20$core..fmt..Debug$u20$for$u20$u8$GT$3fmt17h271d1c938b44f4eaE():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/fmt/num.rs:147
   4:	4608      	mov	r0, r1
   6:	460c      	mov	r4, r1
   8:	f7ff fffe 	bl	0 <_ZN4core3fmt9Formatter15debug_lower_hex17h6ead2f28bb05b574E>
   c:	b128      	cbz	r0, 1a <_ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17hef1b000013b2e9f1E+0x1a>
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/fmt/num.rs:148
   e:	4628      	mov	r0, r5
  10:	4621      	mov	r1, r4
  12:	e8bd 40b0 	ldmia.w	sp!, {r4, r5, r7, lr}
  16:	f7ff bffe 	b.w	0 <_ZN4core3fmt3num52_$LT$impl$u20$core..fmt..LowerHex$u20$for$u20$u8$GT$3fmt17he275dc913fe9b8e5E>
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/fmt/num.rs:149
  1a:	4620      	mov	r0, r4
  1c:	f7ff fffe 	bl	0 <_ZN4core3fmt9Formatter15debug_upper_hex17hd6d96e6aa5cb78d8E>
  20:	b128      	cbz	r0, 2e <_ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17hef1b000013b2e9f1E+0x2e>
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/fmt/num.rs:150
  22:	4628      	mov	r0, r5
  24:	4621      	mov	r1, r4
  26:	e8bd 40b0 	ldmia.w	sp!, {r4, r5, r7, lr}
  2a:	f7ff bffe 	b.w	0 <_ZN4core3fmt3num52_$LT$impl$u20$core..fmt..UpperHex$u20$for$u20$u8$GT$3fmt17h1d24bfddebe6efa8E>
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/fmt/num.rs:152
  2e:	4628      	mov	r0, r5
  30:	4621      	mov	r1, r4
  32:	e8bd 40b0 	ldmia.w	sp!, {r4, r5, r7, lr}
  36:	f7ff bffe 	b.w	0 <_ZN4core3fmt3num3imp51_$LT$impl$u20$core..fmt..Display$u20$for$u20$u8$GT$3fmt17heb4d046d241d78d0E>

Disassembly of section .text._ZN86_$LT$mylib..mynewt..encoding..json..json_encoder$u20$as$u20$core..default..Default$GT$7default17h3a86dbb2a8a8164dE:

00000000 <_ZN86_$LT$mylib..mynewt..encoding..json..json_encoder$u20$as$u20$core..default..Default$GT$7default17h3a86dbb2a8a8164dE>:
_ZN86_$LT$mylib..mynewt..encoding..json..json_encoder$u20$as$u20$core..default..Default$GT$7default17h3a86dbb2a8a8164dE():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/encoding/json.rs:212
    pub je_arg: *mut ::cty::c_void,
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 1usize], u8>,
    pub je_encode_buf: [::cty::c_char; 64usize],
}
impl Default for json_encoder {
    fn default() -> Self {
   0:	b580      	push	{r7, lr}
_ZN4core3mem6zeroed17hdfac71dcca955acbE():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/mem.rs:447
   2:	214c      	movs	r1, #76	; 0x4c
   4:	f7ff fffe 	bl	0 <__aeabi_memclr4>
_ZN86_$LT$mylib..mynewt..encoding..json..json_encoder$u20$as$u20$core..default..Default$GT$7default17h3a86dbb2a8a8164dE():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/encoding/json.rs:214
        unsafe { ::core::mem::zeroed() }
    }
   8:	bd80      	pop	{r7, pc}

Disassembly of section .text._ZN85_$LT$mylib..mynewt..encoding..json..json_enum_t$u20$as$u20$core..default..Default$GT$7default17hbada56f05cb58551E:

00000000 <_ZN85_$LT$mylib..mynewt..encoding..json..json_enum_t$u20$as$u20$core..default..Default$GT$7default17hbada56f05cb58551E>:
_ZN85_$LT$mylib..mynewt..encoding..json..json_enum_t$u20$as$u20$core..default..Default$GT$7default17hbada56f05cb58551E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/encoding/json.rs:296
    pub value: ::cty::c_longlong,
}
impl Default for json_enum_t {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
   0:	2000      	movs	r0, #0
   2:	2100      	movs	r1, #0
   4:	2200      	movs	r2, #0
   6:	4770      	bx	lr

Disassembly of section .text._ZN114_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17he12df112c375aa63E:

00000000 <_ZN114_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17he12df112c375aa63E>:
_ZN114_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17he12df112c375aa63E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/encoding/json.rs:322
    pub subtype: *const json_attr_t,
    pub base: *mut ::cty::c_char,
    pub stride: usize,
}
impl Default for json_array_t__bindgen_ty_1__bindgen_ty_1 {
    fn default() -> Self {
   0:	2100      	movs	r1, #0
_ZN4core3mem6zeroed17he79a03dc3ba22654E():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/mem.rs:447
   2:	e9c0 1100 	strd	r1, r1, [r0]
   6:	6081      	str	r1, [r0, #8]
_ZN114_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17he12df112c375aa63E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/encoding/json.rs:324
        unsafe { ::core::mem::zeroed() }
    }
   8:	4770      	bx	lr

Disassembly of section .text._ZN100_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h667ef8f6053cc85dE:

00000000 <_ZN100_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h667ef8f6053cc85dE>:
_ZN100_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h667ef8f6053cc85dE():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/encoding/json.rs:374
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
impl Default for json_array_t__bindgen_ty_1 {
    fn default() -> Self {
   0:	2100      	movs	r1, #0
_ZN4core3mem6zeroed17h9d49fe59e7a448bdE():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/mem.rs:447
   2:	e9c0 1100 	strd	r1, r1, [r0]
   6:	e9c0 1102 	strd	r1, r1, [r0, #8]
   a:	e9c0 1104 	strd	r1, r1, [r0, #16]
_ZN100_$LT$mylib..mynewt..encoding..json..json_array_t__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h667ef8f6053cc85dE():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/encoding/json.rs:376
        unsafe { ::core::mem::zeroed() }
    }
   e:	4770      	bx	lr

Disassembly of section .text._ZN86_$LT$mylib..mynewt..encoding..json..json_array_t$u20$as$u20$core..default..Default$GT$7default17h9ed2b02adbdc200eE:

00000000 <_ZN86_$LT$mylib..mynewt..encoding..json..json_array_t$u20$as$u20$core..default..Default$GT$7default17h9ed2b02adbdc200eE>:
_ZN86_$LT$mylib..mynewt..encoding..json..json_array_t$u20$as$u20$core..default..Default$GT$7default17h9ed2b02adbdc200eE():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/encoding/json.rs:379
}
impl Default for json_array_t {
    fn default() -> Self {
   0:	b580      	push	{r7, lr}
_ZN4core3mem6zeroed17hbedf3580ab81a216E():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/mem.rs:447
   2:	2128      	movs	r1, #40	; 0x28
   4:	f7ff fffe 	bl	0 <__aeabi_memclr8>
_ZN86_$LT$mylib..mynewt..encoding..json..json_array_t$u20$as$u20$core..default..Default$GT$7default17h9ed2b02adbdc200eE():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/encoding/json.rs:381
        unsafe { ::core::mem::zeroed() }
    }
   8:	bd80      	pop	{r7, pc}

Disassembly of section .text._ZN99_$LT$mylib..mynewt..encoding..json..json_attr_t__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hf95111df9d32b5bcE:

00000000 <_ZN99_$LT$mylib..mynewt..encoding..json..json_attr_t__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hf95111df9d32b5bcE>:
_ZN99_$LT$mylib..mynewt..encoding..json..json_attr_t__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hf95111df9d32b5bcE():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/encoding/json.rs:406
    pub array: __BindgenUnionField<json_array_t>,
    pub offset: __BindgenUnionField<usize>,
    pub bindgen_union_field: [u64; 6usize],
}
impl Default for json_attr_t__bindgen_ty_1 {
    fn default() -> Self {
   0:	b580      	push	{r7, lr}
_ZN4core3mem6zeroed17h300ab67281ab2e1fE():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/mem.rs:447
   2:	2130      	movs	r1, #48	; 0x30
   4:	f7ff fffe 	bl	0 <__aeabi_memclr8>
_ZN99_$LT$mylib..mynewt..encoding..json..json_attr_t__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hf95111df9d32b5bcE():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/encoding/json.rs:408
        unsafe { ::core::mem::zeroed() }
    }
   8:	bd80      	pop	{r7, pc}

Disassembly of section .text._ZN85_$LT$mylib..mynewt..encoding..json..json_attr_t$u20$as$u20$core..default..Default$GT$7default17hf2866f3a6beda229E:

00000000 <_ZN85_$LT$mylib..mynewt..encoding..json..json_attr_t$u20$as$u20$core..default..Default$GT$7default17hf2866f3a6beda229E>:
_ZN85_$LT$mylib..mynewt..encoding..json..json_attr_t$u20$as$u20$core..default..Default$GT$7default17hf2866f3a6beda229E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/encoding/json.rs:426
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
impl Default for json_attr_t {
    fn default() -> Self {
   0:	b580      	push	{r7, lr}
_ZN4core3mem6zeroed17h042424392d1317a3E():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/mem.rs:447
   2:	2150      	movs	r1, #80	; 0x50
   4:	f7ff fffe 	bl	0 <__aeabi_memclr8>
_ZN85_$LT$mylib..mynewt..encoding..json..json_attr_t$u20$as$u20$core..default..Default$GT$7default17hf2866f3a6beda229E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/encoding/json.rs:428
        unsafe { ::core::mem::zeroed() }
    }
   8:	bd80      	pop	{r7, pc}

Disassembly of section .text._ZN78_$LT$mylib..mynewt..kernel..os..os_event$u20$as$u20$core..default..Default$GT$7default17ha9c2a22a0aef1179E:

00000000 <_ZN78_$LT$mylib..mynewt..kernel..os..os_event$u20$as$u20$core..default..Default$GT$7default17ha9c2a22a0aef1179E>:
_ZN78_$LT$mylib..mynewt..kernel..os..os_event$u20$as$u20$core..default..Default$GT$7default17ha9c2a22a0aef1179E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/kernel/os.rs:409
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
impl Default for os_event {
    fn default() -> Self {
   0:	2100      	movs	r1, #0
_ZN4core3mem6zeroed17hde09b20164e48890E():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/mem.rs:447
   2:	e9c0 1100 	strd	r1, r1, [r0]
   6:	e9c0 1102 	strd	r1, r1, [r0, #8]
_ZN78_$LT$mylib..mynewt..kernel..os..os_event$u20$as$u20$core..default..Default$GT$7default17ha9c2a22a0aef1179E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/kernel/os.rs:411
        unsafe { ::core::mem::zeroed() }
    }
   a:	4770      	bx	lr

Disassembly of section .text._ZN80_$LT$mylib..mynewt..kernel..os..os_callout$u20$as$u20$core..default..Default$GT$7default17h35fb82015c01a0aaE:

00000000 <_ZN80_$LT$mylib..mynewt..kernel..os..os_callout$u20$as$u20$core..default..Default$GT$7default17h35fb82015c01a0aaE>:
_ZN80_$LT$mylib..mynewt..kernel..os..os_callout$u20$as$u20$core..default..Default$GT$7default17h35fb82015c01a0aaE():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/kernel/os.rs:541
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
impl Default for os_callout {
    fn default() -> Self {
   0:	2100      	movs	r1, #0
_ZN4core3mem6zeroed17h16df9f0bb14871d1E():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/mem.rs:447
   2:	e9c0 1100 	strd	r1, r1, [r0]
   6:	e9c0 1102 	strd	r1, r1, [r0, #8]
   a:	e9c0 1104 	strd	r1, r1, [r0, #16]
   e:	e9c0 1106 	strd	r1, r1, [r0, #24]
_ZN80_$LT$mylib..mynewt..kernel..os..os_callout$u20$as$u20$core..default..Default$GT$7default17h35fb82015c01a0aaE():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/kernel/os.rs:543
        unsafe { ::core::mem::zeroed() }
    }
  12:	4770      	bx	lr

Disassembly of section .text._ZN79_$LT$mylib..mynewt..kernel..os..hal_timer$u20$as$u20$core..default..Default$GT$7default17h662e239b89e341a8E:

00000000 <_ZN79_$LT$mylib..mynewt..kernel..os..hal_timer$u20$as$u20$core..default..Default$GT$7default17h662e239b89e341a8E>:
_ZN79_$LT$mylib..mynewt..kernel..os..hal_timer$u20$as$u20$core..default..Default$GT$7default17h662e239b89e341a8E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/kernel/os.rs:642
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
impl Default for hal_timer {
    fn default() -> Self {
   0:	2100      	movs	r1, #0
_ZN4core3mem6zeroed17he045c8c5fc9a74b0E():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/mem.rs:447
   2:	e9c0 1100 	strd	r1, r1, [r0]
   6:	e9c0 1102 	strd	r1, r1, [r0, #8]
   a:	e9c0 1104 	strd	r1, r1, [r0, #16]
_ZN79_$LT$mylib..mynewt..kernel..os..hal_timer$u20$as$u20$core..default..Default$GT$7default17h662e239b89e341a8E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/kernel/os.rs:644
        unsafe { ::core::mem::zeroed() }
    }
   e:	4770      	bx	lr

Disassembly of section .text._ZN76_$LT$mylib..mynewt..kernel..os..os_dev$u20$as$u20$core..default..Default$GT$7default17h6796a90f25049da8E:

00000000 <_ZN76_$LT$mylib..mynewt..kernel..os..os_dev$u20$as$u20$core..default..Default$GT$7default17h6796a90f25049da8E>:
_ZN76_$LT$mylib..mynewt..kernel..os..os_dev$u20$as$u20$core..default..Default$GT$7default17h6796a90f25049da8E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/kernel/os.rs:812
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
impl Default for os_dev {
    fn default() -> Self {
   0:	b580      	push	{r7, lr}
_ZN4core3mem6zeroed17h5ff4b613dca1eedbE():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/mem.rs:447
   2:	2124      	movs	r1, #36	; 0x24
   4:	f7ff fffe 	bl	0 <__aeabi_memclr4>
_ZN76_$LT$mylib..mynewt..kernel..os..os_dev$u20$as$u20$core..default..Default$GT$7default17h6796a90f25049da8E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/kernel/os.rs:814
        unsafe { ::core::mem::zeroed() }
    }
   8:	bd80      	pop	{r7, pc}

Disassembly of section .text._ZN77_$LT$mylib..mynewt..kernel..os..os_mbuf$u20$as$u20$core..default..Default$GT$7default17h148a6d1254104847E:

00000000 <_ZN77_$LT$mylib..mynewt..kernel..os..os_mbuf$u20$as$u20$core..default..Default$GT$7default17h148a6d1254104847E>:
_ZN77_$LT$mylib..mynewt..kernel..os..os_mbuf$u20$as$u20$core..default..Default$GT$7default17h148a6d1254104847E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/kernel/os.rs:1040
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
impl Default for os_mbuf {
    fn default() -> Self {
   0:	2100      	movs	r1, #0
_ZN4core3mem6zeroed17h4e7d3f44c9f5617aE():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/mem.rs:447
   2:	e9c0 1100 	strd	r1, r1, [r0]
   6:	e9c0 1102 	strd	r1, r1, [r0, #8]
_ZN77_$LT$mylib..mynewt..kernel..os..os_mbuf$u20$as$u20$core..default..Default$GT$7default17h148a6d1254104847E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/kernel/os.rs:1042
        unsafe { ::core::mem::zeroed() }
    }
   a:	4770      	bx	lr

Disassembly of section .text._ZN80_$LT$mylib..mynewt..kernel..os..os_mempool$u20$as$u20$core..default..Default$GT$7default17ha84ccbb9e7b22964E:

00000000 <_ZN80_$LT$mylib..mynewt..kernel..os..os_mempool$u20$as$u20$core..default..Default$GT$7default17ha84ccbb9e7b22964E>:
_ZN80_$LT$mylib..mynewt..kernel..os..os_mempool$u20$as$u20$core..default..Default$GT$7default17ha84ccbb9e7b22964E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/kernel/os.rs:1521
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
impl Default for os_mempool {
    fn default() -> Self {
   0:	2100      	movs	r1, #0
_ZN4core3mem6zeroed17h0d783c8dfc17ff07E():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/mem.rs:447
   2:	e9c0 1100 	strd	r1, r1, [r0]
   6:	e9c0 1102 	strd	r1, r1, [r0, #8]
   a:	e9c0 1104 	strd	r1, r1, [r0, #16]
   e:	6181      	str	r1, [r0, #24]
_ZN80_$LT$mylib..mynewt..kernel..os..os_mempool$u20$as$u20$core..default..Default$GT$7default17ha84ccbb9e7b22964E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/kernel/os.rs:1523
        unsafe { ::core::mem::zeroed() }
    }
  10:	4770      	bx	lr

Disassembly of section .text._ZN85_$LT$mylib..mynewt..kernel..os..os_sanity_check$u20$as$u20$core..default..Default$GT$7default17hd1233b47a9d8cbcbE:

00000000 <_ZN85_$LT$mylib..mynewt..kernel..os..os_sanity_check$u20$as$u20$core..default..Default$GT$7default17hd1233b47a9d8cbcbE>:
_ZN85_$LT$mylib..mynewt..kernel..os..os_sanity_check$u20$as$u20$core..default..Default$GT$7default17hd1233b47a9d8cbcbE():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/kernel/os.rs:1780
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
impl Default for os_sanity_check {
    fn default() -> Self {
   0:	2100      	movs	r1, #0
_ZN4core3mem6zeroed17h8b40ea82a9904c0dE():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/mem.rs:447
   2:	e9c0 1100 	strd	r1, r1, [r0]
   6:	e9c0 1102 	strd	r1, r1, [r0, #8]
   a:	6101      	str	r1, [r0, #16]
_ZN85_$LT$mylib..mynewt..kernel..os..os_sanity_check$u20$as$u20$core..default..Default$GT$7default17hd1233b47a9d8cbcbE():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/kernel/os.rs:1782
        unsafe { ::core::mem::zeroed() }
    }
   c:	4770      	bx	lr

Disassembly of section .text._ZN77_$LT$mylib..mynewt..kernel..os..os_task$u20$as$u20$core..default..Default$GT$7default17hbcc6978df783f1d8E:

00000000 <_ZN77_$LT$mylib..mynewt..kernel..os..os_task$u20$as$u20$core..default..Default$GT$7default17hbcc6978df783f1d8E>:
_ZN77_$LT$mylib..mynewt..kernel..os..os_task$u20$as$u20$core..default..Default$GT$7default17hbcc6978df783f1d8E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/kernel/os.rs:1918
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
impl Default for os_task {
    fn default() -> Self {
   0:	b580      	push	{r7, lr}
_ZN4core3mem6zeroed17h20b61e8abdfcdcd5E():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/mem.rs:447
   2:	2150      	movs	r1, #80	; 0x50
   4:	f7ff fffe 	bl	0 <__aeabi_memclr4>
_ZN77_$LT$mylib..mynewt..kernel..os..os_task$u20$as$u20$core..default..Default$GT$7default17hbcc6978df783f1d8E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/kernel/os.rs:1920
        unsafe { ::core::mem::zeroed() }
    }
   8:	bd80      	pop	{r7, pc}

Disassembly of section .text._ZN76_$LT$mylib..mynewt..kernel..os..os_sem$u20$as$u20$core..default..Default$GT$7default17h5c8e87c2628b6e14E:

00000000 <_ZN76_$LT$mylib..mynewt..kernel..os..os_sem$u20$as$u20$core..default..Default$GT$7default17h5c8e87c2628b6e14E>:
_ZN76_$LT$mylib..mynewt..kernel..os..os_sem$u20$as$u20$core..default..Default$GT$7default17h5c8e87c2628b6e14E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/kernel/os.rs:2131
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
impl Default for os_sem {
    fn default() -> Self {
   0:	2100      	movs	r1, #0
_ZN4core3mem6zeroed17h683df8b7d7843087E():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/mem.rs:447
   2:	e9c0 1100 	strd	r1, r1, [r0]
_ZN76_$LT$mylib..mynewt..kernel..os..os_sem$u20$as$u20$core..default..Default$GT$7default17h5c8e87c2628b6e14E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/kernel/os.rs:2133
        unsafe { ::core::mem::zeroed() }
    }
   6:	4770      	bx	lr

Disassembly of section .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE:

00000000 <_ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE>:
_ZN100_$LT$mylib..mynewt..hw..sensor..bindings..os_dev__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h330f6cf2332e2d1aE():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/hw/sensor/bindings.rs:207
    pub stqe_next: *mut os_dev,
}
impl Default for os_dev__bindgen_ty_1 {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
   0:	2000      	movs	r0, #0
   2:	4770      	bx	lr

Disassembly of section .text._ZN93_$LT$mylib..mynewt..hw..sensor..bindings..sensor_data_t$u20$as$u20$core..default..Default$GT$7default17hb4bfaef90e32f038E:

00000000 <_ZN93_$LT$mylib..mynewt..hw..sensor..bindings..sensor_data_t$u20$as$u20$core..default..Default$GT$7default17hb4bfaef90e32f038E>:
_ZN93_$LT$mylib..mynewt..hw..sensor..bindings..sensor_data_t$u20$as$u20$core..default..Default$GT$7default17hb4bfaef90e32f038E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/hw/sensor/bindings.rs:359
    pub spd: __BindgenUnionField<*mut sensor_press_data>,
    pub srhd: __BindgenUnionField<*mut sensor_humid_data>,
    pub bindgen_union_field: u64,
}
impl Default for sensor_data_t {
    fn default() -> Self {
   0:	2100      	movs	r1, #0
_ZN4core3mem6zeroed17h2b423228324b0bdaE():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/mem.rs:447
   2:	e9c0 1100 	strd	r1, r1, [r0]
_ZN93_$LT$mylib..mynewt..hw..sensor..bindings..sensor_data_t$u20$as$u20$core..default..Default$GT$7default17hb4bfaef90e32f038E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/hw/sensor/bindings.rs:361
        unsafe { ::core::mem::zeroed() }
    }
   6:	4770      	bx	lr

Disassembly of section .text._ZN95_$LT$mylib..mynewt..hw..sensor..bindings..sensor_listener$u20$as$u20$core..default..Default$GT$7default17h1dd4f66caf63ca67E:

00000000 <_ZN95_$LT$mylib..mynewt..hw..sensor..bindings..sensor_listener$u20$as$u20$core..default..Default$GT$7default17h1dd4f66caf63ca67E>:
_ZN95_$LT$mylib..mynewt..hw..sensor..bindings..sensor_listener$u20$as$u20$core..default..Default$GT$7default17h1dd4f66caf63ca67E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/hw/sensor/bindings.rs:443
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
impl Default for sensor_listener {
    fn default() -> Self {
   0:	2100      	movs	r1, #0
_ZN4core3mem6zeroed17h58d70380eab5e2a6E():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/mem.rs:447
   2:	e9c0 1100 	strd	r1, r1, [r0]
   6:	e9c0 1102 	strd	r1, r1, [r0, #8]
   a:	e9c0 1104 	strd	r1, r1, [r0, #16]
_ZN95_$LT$mylib..mynewt..hw..sensor..bindings..sensor_listener$u20$as$u20$core..default..Default$GT$7default17h1dd4f66caf63ca67E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/hw/sensor/bindings.rs:445
        unsafe { ::core::mem::zeroed() }
    }
   e:	4770      	bx	lr

Disassembly of section .text._ZN98_$LT$mylib..mynewt..hw..sensor..bindings..sensor_type_traits$u20$as$u20$core..default..Default$GT$7default17h604a349a45bc2964E:

00000000 <_ZN98_$LT$mylib..mynewt..hw..sensor..bindings..sensor_type_traits$u20$as$u20$core..default..Default$GT$7default17h604a349a45bc2964E>:
_ZN98_$LT$mylib..mynewt..hw..sensor..bindings..sensor_type_traits$u20$as$u20$core..default..Default$GT$7default17h604a349a45bc2964E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/hw/sensor/bindings.rs:503
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
impl Default for sensor_type_traits {
    fn default() -> Self {
   0:	b580      	push	{r7, lr}
_ZN4core3mem6zeroed17h1d19c7d52964ac37E():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/mem.rs:447
   2:	2130      	movs	r1, #48	; 0x30
   4:	f7ff fffe 	bl	0 <__aeabi_memclr8>
_ZN98_$LT$mylib..mynewt..hw..sensor..bindings..sensor_type_traits$u20$as$u20$core..default..Default$GT$7default17h604a349a45bc2964E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/hw/sensor/bindings.rs:505
        unsafe { ::core::mem::zeroed() }
    }
   8:	bd80      	pop	{r7, pc}

Disassembly of section .text._ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_ev_ctx$u20$as$u20$core..default..Default$GT$7default17ha4b50f23ab08f5e7E:

00000000 <_ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_ev_ctx$u20$as$u20$core..default..Default$GT$7default17ha4b50f23ab08f5e7E>:
_ZN100_$LT$mylib..mynewt..hw..sensor..bindings..sensor_notify_ev_ctx$u20$as$u20$core..default..Default$GT$7default17ha4b50f23ab08f5e7E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/hw/sensor/bindings.rs:515
    pub snec_evtype: sensor_event_type_t,
}
impl Default for sensor_notify_ev_ctx {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
   0:	2000      	movs	r0, #0
   2:	2100      	movs	r1, #0
   4:	4770      	bx	lr

Disassembly of section .text._ZN86_$LT$mylib..mynewt..hw..sensor..bindings..sensor$u20$as$u20$core..default..Default$GT$7default17h3972b4100904ce9dE:

00000000 <_ZN86_$LT$mylib..mynewt..hw..sensor..bindings..sensor$u20$as$u20$core..default..Default$GT$7default17h3972b4100904ce9dE>:
_ZN86_$LT$mylib..mynewt..hw..sensor..bindings..sensor$u20$as$u20$core..default..Default$GT$7default17h3972b4100904ce9dE():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/hw/sensor/bindings.rs:739
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
impl Default for sensor {
    fn default() -> Self {
   0:	b580      	push	{r7, lr}
_ZN4core3mem6zeroed17h081f11805e8da9edE():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/mem.rs:447
   2:	2188      	movs	r1, #136	; 0x88
   4:	f7ff fffe 	bl	0 <__aeabi_memclr8>
_ZN86_$LT$mylib..mynewt..hw..sensor..bindings..sensor$u20$as$u20$core..default..Default$GT$7default17h3972b4100904ce9dE():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/hw/sensor/bindings.rs:741
        unsafe { ::core::mem::zeroed() }
    }
   8:	bd80      	pop	{r7, pc}

Disassembly of section .text._ZN93_$LT$mylib..mynewt..hw..sensor..bindings.._bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hfe61a3a2e7f05b3cE:

00000000 <_ZN93_$LT$mylib..mynewt..hw..sensor..bindings.._bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hfe61a3a2e7f05b3cE>:
_ZN93_$LT$mylib..mynewt..hw..sensor..bindings.._bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hfe61a3a2e7f05b3cE():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/hw/sensor/bindings.rs:1833
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
impl Default for _bindgen_ty_1 {
    fn default() -> Self {
   0:	b580      	push	{r7, lr}
_ZN4core3mem6zeroed17h31ea305547e32d20E():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/mem.rs:447
   2:	2134      	movs	r1, #52	; 0x34
   4:	f7ff fffe 	bl	0 <__aeabi_memclr4>
_ZN93_$LT$mylib..mynewt..hw..sensor..bindings.._bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17hfe61a3a2e7f05b3cE():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/hw/sensor/bindings.rs:1835
        unsafe { ::core::mem::zeroed() }
    }
   8:	bd80      	pop	{r7, pc}

Disassembly of section .text._ZN5mylib6mynewt2hw6sensor21null_sensor_data_func17he576af080a279986E:

00000000 <_ZN5mylib6mynewt2hw6sensor21null_sensor_data_func17he576af080a279986E>:
_ZN5mylib6mynewt2hw6sensor21null_sensor_data_func17he576af080a279986E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/hw/sensor.rs:88
extern fn null_sensor_data_func(
    _sensor: sensor_ptr, 
    _arg: sensor_arg, 
    _sensor_data: sensor_data_ptr, 
    _sensor_type: sensor_type_t) -> i32
    { 0 }
   0:	2000      	movs	r0, #0
   2:	4770      	bx	lr

Disassembly of section .text._ZN101_$LT$mylib..mynewt..libs..sensor_coap..json_value__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h7186c454935d415bE:

00000000 <_ZN101_$LT$mylib..mynewt..libs..sensor_coap..json_value__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h7186c454935d415bE>:
_ZN101_$LT$mylib..mynewt..libs..sensor_coap..json_value__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h7186c454935d415bE():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/libs/sensor_coap.rs:430
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
impl Default for json_value__bindgen_ty_1 {
    fn default() -> Self {
   0:	2100      	movs	r1, #0
_ZN4core3mem6zeroed17h0baece6fa5847311E():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/mem.rs:447
   2:	e9c0 1100 	strd	r1, r1, [r0]
   6:	e9c0 1102 	strd	r1, r1, [r0, #8]
_ZN101_$LT$mylib..mynewt..libs..sensor_coap..json_value__bindgen_ty_1$u20$as$u20$core..default..Default$GT$7default17h7186c454935d415bE():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/libs/sensor_coap.rs:432
        unsafe { ::core::mem::zeroed() }
    }
   a:	4770      	bx	lr

Disassembly of section .text._ZN104_$LT$mylib..mynewt..libs..sensor_network..sensor_network_interface$u20$as$u20$core..default..Default$GT$7default17h35426a326eb363b6E:

00000000 <_ZN104_$LT$mylib..mynewt..libs..sensor_network..sensor_network_interface$u20$as$u20$core..default..Default$GT$7default17h35426a326eb363b6E>:
_ZN104_$LT$mylib..mynewt..libs..sensor_network..sensor_network_interface$u20$as$u20$core..default..Default$GT$7default17h35426a326eb363b6E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/libs/sensor_network.rs:40
        ) -> ::cty::c_int,
    >,
    pub transport_registered: u8,
}
impl Default for sensor_network_interface {
    fn default() -> Self {
   0:	2100      	movs	r1, #0
_ZN4core3mem6zeroed17h7dc4380bca9ca9cdE():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/mem.rs:447
   2:	e9c0 1100 	strd	r1, r1, [r0]
   6:	e9c0 1102 	strd	r1, r1, [r0, #8]
   a:	6101      	str	r1, [r0, #16]
_ZN104_$LT$mylib..mynewt..libs..sensor_network..sensor_network_interface$u20$as$u20$core..default..Default$GT$7default17h35426a326eb363b6E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/libs/sensor_network.rs:42
        unsafe { ::core::mem::zeroed() }
    }
   c:	4770      	bx	lr

Disassembly of section .text._ZN5mylib6mynewt6result95_$LT$impl$u20$core..convert..From$LT$mylib..mynewt..result..MynewtError$GT$$u20$for$u20$i32$GT$4from17he768babb092a5c90E:

00000000 <_ZN5mylib6mynewt6result95_$LT$impl$u20$core..convert..From$LT$mylib..mynewt..result..MynewtError$GT$$u20$for$u20$i32$GT$4from17he768babb092a5c90E>:
_ZN5mylib6mynewt6result95_$LT$impl$u20$core..convert..From$LT$mylib..mynewt..result..MynewtError$GT$$u20$for$u20$i32$GT$4from17he768babb092a5c90E():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt.rs:57
    /// Cast `MynewtError` to `i32`
    impl From<MynewtError> for i32 {
        /// Cast `MynewtError` to `i32`
        fn from(err: MynewtError) -> Self {
            err as i32
        }
   0:	4770      	bx	lr

Disassembly of section .text._ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E:

00000000 <_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E>:
_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E():
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:80
///  This listener function is called by Mynewt every 10 seconds (for local sensors) or when sensor data is received
///  (for Remote Sensors).  Mynewt has fetched the raw or computed temperature value, passed through `sensor_data`.
///  If this is a Sensor Node, we send the sensor data to the Collector Node.
///  If this is a Collector Node or Standalone Node, we send the sensor data to the CoAP server.  
///  Return 0 if we have processed the sensor data successfully.
extern fn read_temperature(sensor: sensor_ptr, _arg: sensor_arg, 
   0:	b5f0      	push	{r4, r5, r6, r7, lr}
   2:	b091      	sub	sp, #68	; 0x44
   4:	4604      	mov	r4, r0
_ZN5mylib4base13console_print17h53afd0cf661b2c25E():
/mnt/c/stm32bluepill-mynewt-sensor/src/base.rs:18
///  Display message `msg` on the Arm Semihosting console (via OpenOCD).
pub fn console_print(msg: &[u8]) {
    let len = msg.len();
    unsafe {
        //  Call the Semihosting Console API, which is unsafe.
        console_buffer(msg.as_ptr(), len as u32);
   6:	f240 0000 	movw	r0, #0
   a:	f2c0 0000 	movt	r0, #0
   e:	2111      	movs	r1, #17
  10:	4616      	mov	r6, r2
  12:	f7ff fffe 	bl	0 <console_buffer>
/mnt/c/stm32bluepill-mynewt-sensor/src/base.rs:19
        console_flush();  //  TODO: Remove this.
  16:	f7ff fffe 	bl	0 <console_flush>
_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E():
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:85
    sensor_data: sensor_data_ptr, sensor_type: sensor_type_t) -> MynewtError {
    console_print(b"read_temperature\n");
    //  Check that the temperature data is valid.
    //  TODO
    if unsafe { is_null_sensor_data(sensor_data) } { return MynewtError::SYS_EINVAL; }  //  Exit if data is missing
  1a:	4630      	mov	r0, r6
  1c:	f7ff fffe 	bl	0 <is_null_sensor_data>
  20:	b118      	cbz	r0, 2a <_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E+0x2a>
  22:	f06f 0001 	mvn.w	r0, #1
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:116
            return MynewtError::SYS_EOK; 
        }            
    }
    //  Return 0 to Mynewt to indicate no error.  Should not end with a semicolon (;).
    MynewtError::SYS_EOK
}
  26:	b011      	add	sp, #68	; 0x44
  28:	bdf0      	pop	{r4, r5, r6, r7, pc}
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:86
    assert!(unsafe { !is_null_sensor(sensor) });
  2a:	4620      	mov	r0, r4
  2c:	f7ff fffe 	bl	0 <is_null_sensor>
  30:	2800      	cmp	r0, #0
  32:	f040 809b 	bne.w	16c <_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E+0x16c>
  36:	e9dd 1016 	ldrd	r1, r0, [sp, #88]	; 0x58
_ZN5mylib13listen_sensor15get_temperature17had1038eb151d12bfE():
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:126
#[allow(unreachable_patterns)]
#[allow(unused_variables)]
fn get_temperature(sensor_data: sensor_data_ptr, sensor_type: sensor_type_t) -> SensorValue {
    let mut return_value = SensorValue::default();
    match sensor_type {                           //  Is this raw or computed temperature?
        SENSOR_TYPE_AMBIENT_TEMPERATURE_RAW => {  //  If this is raw temperature...
  3a:	f081 6180 	eor.w	r1, r1, #67108864	; 0x4000000
  3e:	ea41 0700 	orr.w	r7, r1, r0
_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E():
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:91
    let device = unsafe { sensor_get_device(sensor) };
  42:	4620      	mov	r0, r4
  44:	f7ff fffe 	bl	0 <sensor_get_device>
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:92
    let device_name_ptr: *const c_char = unsafe { device_get_name(device) };
  48:	f7ff fffe 	bl	0 <device_get_name>
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:93
    let device_name: &CStr = unsafe { CStr::from_ptr(device_name_ptr) };
  4c:	f7ff fffe 	bl	0 <_ZN9cstr_core4CStr8from_ptr17h02056df58ddde440E>
  50:	4604      	mov	r4, r0
  52:	460d      	mov	r5, r1
  54:	2000      	movs	r0, #0
_ZN5mylib13listen_sensor15get_temperature17had1038eb151d12bfE():
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:126
        SENSOR_TYPE_AMBIENT_TEMPERATURE_RAW => {  //  If this is raw temperature...
  56:	b9c7      	cbnz	r7, 8a <_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E+0x8a>
  58:	a905      	add	r1, sp, #20
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:128
            //  Interpret the sensor data as a sensor_temp_raw_data struct that contains raw temp.
            let mut rawtempdata = fill_zero!(sensor_temp_raw_data);
  5a:	f88d 0018 	strb.w	r0, [sp, #24]
  5e:	9005      	str	r0, [sp, #20]
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:129
            let rc = unsafe { get_temp_raw_data(sensor_data, &mut rawtempdata) };
  60:	4630      	mov	r0, r6
  62:	f7ff fffe 	bl	0 <get_temp_raw_data>
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:130
            assert!(rc == 0);
  66:	2800      	cmp	r0, #0
  68:	f040 808e 	bne.w	188 <_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E+0x188>
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:133

            //  Check that the raw temperature data is valid.
            if rawtempdata.strd_temp_raw_is_valid == 0 { return return_value; }  //  Exit if data is not valid
  6c:	f89d 0018 	ldrb.w	r0, [sp, #24]
  70:	2800      	cmp	r0, #0
  72:	f000 8082 	beq.w	17a <_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E+0x17a>
_ZN5mylib4base13console_print17h53afd0cf661b2c25E():
/mnt/c/stm32bluepill-mynewt-sensor/src/base.rs:18
        console_buffer(msg.as_ptr(), len as u32);
  76:	f240 0000 	movw	r0, #0
  7a:	2119      	movs	r1, #25
  7c:	f2c0 0000 	movt	r0, #0
  80:	f7ff fffe 	bl	0 <console_buffer>
/mnt/c/stm32bluepill-mynewt-sensor/src/base.rs:19
        console_flush();  //  TODO: Remove this.
  84:	f7ff fffe 	bl	0 <console_flush>
  88:	e00c      	b.n	a4 <_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E+0xa4>
_ZN5mylib13listen_sensor15get_temperature17had1038eb151d12bfE():
  8a:	a905      	add	r1, sp, #20
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:141
            return_value.val = SensorValueType::Uint(rawtempdata.strd_temp_raw);  //  Raw Temperature in integer (0 to 4095)
            console_print(b"TMP listener got rawtmp \n");  // return_value->int_val);
        },
        SENSOR_TYPE_AMBIENT_TEMPERATURE => {      //  If this is computed temperature...
            //  Interpret the sensor data as a sensor_temp_data struct that contains computed temp.
            let mut tempdata = fill_zero!(sensor_temp_data);
  8c:	f88d 0018 	strb.w	r0, [sp, #24]
  90:	9005      	str	r0, [sp, #20]
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:142
            let rc = unsafe { get_temp_data(sensor_data, &mut tempdata) };
  92:	4630      	mov	r0, r6
  94:	f7ff fffe 	bl	0 <get_temp_data>
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:143
            assert!(rc == 0);
  98:	2800      	cmp	r0, #0
  9a:	d17c      	bne.n	196 <_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E+0x196>
  9c:	f89d 0018 	ldrb.w	r0, [sp, #24]
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:146

            //  Check that the computed temperature data is valid.
            if tempdata.std_temp_is_valid() == 0 { return return_value; }  //  Exit if data is not valid
  a0:	07c0      	lsls	r0, r0, #31
  a2:	d06a      	beq.n	17a <_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E+0x17a>
_ZN5mylib4base13console_print17h53afd0cf661b2c25E():
/mnt/c/stm32bluepill-mynewt-sensor/src/base.rs:18
        console_buffer(msg.as_ptr(), len as u32);
  a4:	f240 0000 	movw	r0, #0
  a8:	2111      	movs	r1, #17
  aa:	f2c0 0000 	movt	r0, #0
  ae:	f7ff fffe 	bl	0 <console_buffer>
/mnt/c/stm32bluepill-mynewt-sensor/src/base.rs:19
        console_flush();  //  TODO: Remove this.
  b2:	f7ff fffe 	bl	0 <console_flush>
  b6:	2000      	movs	r0, #0
_ZN5mylib9send_coap16send_sensor_data17hb3f5ad7bc3c59aa4E():
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:128
pub fn send_sensor_data(sensor_val: &SensorValue, sensor_node: &CStr) -> MynewtResult<()>  {  //  Returns an error code upon error.
    console_print(b"send_sensor_data\n");
    //  TODO: Remove val
    let mut val = fill_zero!(sensor_value);
    //  For Sensor Node: Transmit the sensor data to the Collector Node as CBOR.
    if unsafe { sensor_network::should_send_to_collector(&mut val, sensor_node.as_ptr()) } { 
  b8:	4621      	mov	r1, r4
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:126
    let mut val = fill_zero!(sensor_value);
  ba:	e9cd 0003 	strd	r0, r0, [sp, #12]
  be:	e9cd 0001 	strd	r0, r0, [sp, #4]
  c2:	a801      	add	r0, sp, #4
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:128
    if unsafe { sensor_network::should_send_to_collector(&mut val, sensor_node.as_ptr()) } { 
  c4:	f7ff fffe 	bl	0 <should_send_to_collector>
  c8:	b1b0      	cbz	r0, 30 <_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E+0x30>
_ZN5mylib9send_coap29send_sensor_data_to_collector17hee27b36eedd1b0b3E():
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:297
///  to be transmitted.  Return 0 if successful, `SYS_EAGAIN` if network is not ready yet.
///  The CoAP payload needs to be very compact (under 32 bytes) so it will be encoded in CBOR like this:
///  `{ t: 2870 }`
fn send_sensor_data_to_collector(sensor_val: &SensorValue, _node_id: &CStr) -> MynewtResult<()>  {  //  Returns an error code upon error.
    ////  TODO: if let SensorValueType::None = sensor_val.val { assert!(false); }
    if unsafe { !NETWORK_IS_READY } { return Err(MynewtError::SYS_EAGAIN); }  //  If network is not ready, tell caller (Sensor Listener) to try later.
  ca:	f240 0000 	movw	r0, #0
  ce:	f2c0 0000 	movt	r0, #0
  d2:	7800      	ldrb	r0, [r0, #0]
  d4:	2801      	cmp	r0, #1
  d6:	d139      	bne.n	14c <_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E+0x14c>
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:302

    //  Start composing the CoAP Collector message with the sensor data in the payload.  This will 
    //  block other tasks from composing and posting CoAP messages (through a semaphore).
    //  We only have 1 memory buffer for composing CoAP messages so it needs to be locked.
    let rc = unsafe { sensor_network::init_collector_post() };  assert!(rc);
  d8:	f7ff fffe 	bl	0 <init_collector_post>
  dc:	2800      	cmp	r0, #0
  de:	f000 8094 	beq.w	20a <_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E+0x20a>
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:315
    */

    //  Post the CoAP Collector message to the CoAP Background Task for transmission.  After posting the
    //  message to the background task, we release a semaphore that unblocks other requests
    //  to compose and post CoAP messages.
    let rc = unsafe { sensor_network::do_collector_post() };  assert!(rc);
  e2:	f7ff fffe 	bl	0 <do_collector_post>
  e6:	2800      	cmp	r0, #0
  e8:	f000 8096 	beq.w	218 <_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E+0x218>
_ZN5mylib4base13console_print17h53afd0cf661b2c25E():
/mnt/c/stm32bluepill-mynewt-sensor/src/base.rs:18
        console_buffer(msg.as_ptr(), len as u32);
  ec:	f240 0000 	movw	r0, #0
  f0:	2121      	movs	r1, #33	; 0x21
  f2:	f2c0 0000 	movt	r0, #0
  f6:	e021      	b.n	13c <_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E+0x13c>
_ZN9cstr_core4CStr8to_bytes17h62ad98c7b7c63aecE():
/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cstr_core-0.1.2/src/lib.rs:1033
    /// assert_eq!(c_str.to_bytes(), b"foo");
    /// ```
    #[inline]
    pub fn to_bytes(&self) -> &[u8] {
        let bytes = self.to_bytes_with_nul();
        &bytes[..bytes.len() - 1]
  f8:	1e68      	subs	r0, r5, #1
_ZN99_$LT$core..ops..range..Range$LT$usize$GT$$u20$as$u20$core..slice..SliceIndex$LT$$u5b$T$u5d$$GT$$GT$5index17h0359d5933038e6d6E():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/slice/mod.rs:2745
  fa:	2d00      	cmp	r5, #0
  fc:	d052      	beq.n	1a4 <_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E+0x1a4>
_ZN5mylib9send_coap26send_sensor_data_to_server17h9e7f4cfab2b86312E():
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:156
    assert_ne!(node_id.to_bytes()[0], 0);
  fe:	2800      	cmp	r0, #0
 100:	d054      	beq.n	1ac <_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E+0x1ac>
 102:	7820      	ldrb	r0, [r4, #0]
 104:	2800      	cmp	r0, #0
 106:	d05a      	beq.n	1be <_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E+0x1be>
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:157
    if unsafe { !NETWORK_IS_READY } { return Err(MynewtError::SYS_EAGAIN); }  //  If network is not ready, tell caller (Sensor Listener) to try later.
 108:	f240 0000 	movw	r0, #0
 10c:	f2c0 0000 	movt	r0, #0
 110:	7800      	ldrb	r0, [r0, #0]
 112:	2801      	cmp	r0, #1
 114:	d11a      	bne.n	14c <_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E+0x14c>
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:158
    let device_id_ptr = unsafe { sensor_network::get_device_id() };
 116:	f7ff fffe 	bl	0 <get_device_id>
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:159
    let device_id: &CStr = unsafe { CStr::from_ptr(device_id_ptr) };
 11a:	f7ff fffe 	bl	0 <_ZN9cstr_core4CStr8from_ptr17h02056df58ddde440E>
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:164
    let rc = unsafe { sensor_network::init_server_post(0 as *const c_char) };  assert!(rc);
 11e:	2000      	movs	r0, #0
 120:	f7ff fffe 	bl	0 <init_server_post>
 124:	2800      	cmp	r0, #0
 126:	d07e      	beq.n	226 <_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E+0x226>
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:185
    let rc = unsafe { sensor_network::do_server_post() };  assert!(rc);
 128:	f7ff fffe 	bl	0 <do_server_post>
 12c:	2800      	cmp	r0, #0
 12e:	f000 8081 	beq.w	234 <_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E+0x234>
_ZN5mylib4base13console_print17h53afd0cf661b2c25E():
/mnt/c/stm32bluepill-mynewt-sensor/src/base.rs:18
 132:	f240 0000 	movw	r0, #0
 136:	214b      	movs	r1, #75	; 0x4b
 138:	f2c0 0000 	movt	r0, #0
_ZN5mylib9send_coap16send_sensor_data17hb3f5ad7bc3c59aa4E():
 13c:	f7ff fffe 	bl	0 <console_buffer>
 140:	f7ff fffe 	bl	0 <console_flush>
 144:	2001      	movs	r0, #1
_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E():
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:108
    if let Err(err) = rc {  //  `if let` will assign `err` to the error code inside `rc`
 146:	3006      	adds	r0, #6
 148:	d10d      	bne.n	166 <_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E+0x166>
 14a:	e003      	b.n	154 <_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E+0x154>
 14c:	f06f 0005 	mvn.w	r0, #5
 150:	3006      	adds	r0, #6
 152:	d108      	bne.n	166 <_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E+0x166>
_ZN5mylib4base13console_print17h53afd0cf661b2c25E():
/mnt/c/stm32bluepill-mynewt-sensor/src/base.rs:18
 154:	f240 0000 	movw	r0, #0
 158:	2116      	movs	r1, #22
 15a:	f2c0 0000 	movt	r0, #0
 15e:	f7ff fffe 	bl	0 <console_buffer>
/mnt/c/stm32bluepill-mynewt-sensor/src/base.rs:19
        console_flush();  //  TODO: Remove this.
 162:	f7ff fffe 	bl	0 <console_flush>
_ZN5mylib13listen_sensor16read_temperature17h283273ee5533fd04E():
 166:	2000      	movs	r0, #0
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:116
}
 168:	b011      	add	sp, #68	; 0x44
 16a:	bdf0      	pop	{r4, r5, r6, r7, pc}
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:86
    assert!(unsafe { !is_null_sensor(sensor) });
 16c:	f240 0000 	movw	r0, #0
 170:	f2c0 0000 	movt	r0, #0
 174:	f7ff fffe 	bl	0 <_ZN4core9panicking5panic17h53ca63c6ac6312f8E>
 178:	defe      	udf	#254	; 0xfe
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:98
    if let SensorValueType::None = temp_sensor_value.val { assert!(false); }  //  Invalid type
 17a:	f240 0000 	movw	r0, #0
 17e:	f2c0 0000 	movt	r0, #0
 182:	f7ff fffe 	bl	0 <_ZN4core9panicking5panic17h53ca63c6ac6312f8E>
 186:	defe      	udf	#254	; 0xfe
_ZN5mylib13listen_sensor15get_temperature17had1038eb151d12bfE():
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:130
            assert!(rc == 0);
 188:	f240 0000 	movw	r0, #0
 18c:	f2c0 0000 	movt	r0, #0
 190:	f7ff fffe 	bl	0 <_ZN4core9panicking5panic17h53ca63c6ac6312f8E>
 194:	defe      	udf	#254	; 0xfe
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:143
            assert!(rc == 0);
 196:	f240 0000 	movw	r0, #0
 19a:	f2c0 0000 	movt	r0, #0
 19e:	f7ff fffe 	bl	0 <_ZN4core9panicking5panic17h53ca63c6ac6312f8E>
 1a2:	defe      	udf	#254	; 0xfe
_ZN99_$LT$core..ops..range..Range$LT$usize$GT$$u20$as$u20$core..slice..SliceIndex$LT$$u5b$T$u5d$$GT$$GT$5index17h0359d5933038e6d6E():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/slice/mod.rs:2746
 1a4:	2100      	movs	r1, #0
 1a6:	f7ff fffe 	bl	0 <_ZN4core5slice20slice_index_len_fail17hedb5bb240677a6b7E>
 1aa:	defe      	udf	#254	; 0xfe
_ZN5mylib9send_coap26send_sensor_data_to_server17h9e7f4cfab2b86312E():
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:156
    assert_ne!(node_id.to_bytes()[0], 0);
 1ac:	f240 0000 	movw	r0, #0
 1b0:	2100      	movs	r1, #0
 1b2:	f2c0 0000 	movt	r0, #0
 1b6:	2200      	movs	r2, #0
 1b8:	f7ff fffe 	bl	0 <_ZN4core9panicking18panic_bounds_check17h946762cd0671aec9E>
 1bc:	defe      	udf	#254	; 0xfe
 1be:	f240 0000 	movw	r0, #0
 1c2:	a910      	add	r1, sp, #64	; 0x40
 1c4:	f2c0 0000 	movt	r0, #0
 1c8:	940f      	str	r4, [sp, #60]	; 0x3c
 1ca:	900e      	str	r0, [sp, #56]	; 0x38
 1cc:	e9cd 010c 	strd	r0, r1, [sp, #48]	; 0x30
 1d0:	a80f      	add	r0, sp, #60	; 0x3c
 1d2:	900b      	str	r0, [sp, #44]	; 0x2c
 1d4:	f240 0000 	movw	r0, #0
 1d8:	f2c0 0000 	movt	r0, #0
 1dc:	f240 0100 	movw	r1, #0
 1e0:	9010      	str	r0, [sp, #64]	; 0x40
 1e2:	2002      	movs	r0, #2
_ZN4core3fmt9Arguments6new_v117ha99294a9defa432aE():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/fmt/mod.rs:316
 1e4:	900a      	str	r0, [sp, #40]	; 0x28
 1e6:	a80b      	add	r0, sp, #44	; 0x2c
 1e8:	9009      	str	r0, [sp, #36]	; 0x24
 1ea:	2000      	movs	r0, #0
 1ec:	e9cd 0007 	strd	r0, r0, [sp, #28]
 1f0:	2003      	movs	r0, #3
 1f2:	9006      	str	r0, [sp, #24]
 1f4:	f240 0000 	movw	r0, #0
 1f8:	f2c0 0000 	movt	r0, #0
_ZN5mylib9send_coap26send_sensor_data_to_server17h9e7f4cfab2b86312E():
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:156
 1fc:	f2c0 0100 	movt	r1, #0
_ZN4core3fmt9Arguments6new_v117ha99294a9defa432aE():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/fmt/mod.rs:316
 200:	9005      	str	r0, [sp, #20]
 202:	a805      	add	r0, sp, #20
_ZN5mylib9send_coap26send_sensor_data_to_server17h9e7f4cfab2b86312E():
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:156
 204:	f7ff fffe 	bl	0 <_ZN4core9panicking9panic_fmt17h6b4d8e87b0965449E>
 208:	defe      	udf	#254	; 0xfe
_ZN5mylib9send_coap29send_sensor_data_to_collector17hee27b36eedd1b0b3E():
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:302
    let rc = unsafe { sensor_network::init_collector_post() };  assert!(rc);
 20a:	f240 0000 	movw	r0, #0
 20e:	f2c0 0000 	movt	r0, #0
 212:	f7ff fffe 	bl	0 <_ZN4core9panicking5panic17h53ca63c6ac6312f8E>
 216:	defe      	udf	#254	; 0xfe
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:315
    let rc = unsafe { sensor_network::do_collector_post() };  assert!(rc);
 218:	f240 0000 	movw	r0, #0
 21c:	f2c0 0000 	movt	r0, #0
 220:	f7ff fffe 	bl	0 <_ZN4core9panicking5panic17h53ca63c6ac6312f8E>
 224:	defe      	udf	#254	; 0xfe
_ZN5mylib9send_coap26send_sensor_data_to_server17h9e7f4cfab2b86312E():
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:164
    let rc = unsafe { sensor_network::init_server_post(0 as *const c_char) };  assert!(rc);
 226:	f240 0000 	movw	r0, #0
 22a:	f2c0 0000 	movt	r0, #0
 22e:	f7ff fffe 	bl	0 <_ZN4core9panicking5panic17h53ca63c6ac6312f8E>
 232:	defe      	udf	#254	; 0xfe
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:185
    let rc = unsafe { sensor_network::do_server_post() };  assert!(rc);
 234:	f240 0000 	movw	r0, #0
 238:	f2c0 0000 	movt	r0, #0
 23c:	f7ff fffe 	bl	0 <_ZN4core9panicking5panic17h53ca63c6ac6312f8E>
 240:	defe      	udf	#254	; 0xfe

Disassembly of section .text._ZN5mylib9send_coap17network_task_func17hd9a1eeab35a857d1E:

00000000 <_ZN5mylib9send_coap17network_task_func17hd9a1eeab35a857d1E>:
_ZN5mylib9send_coap17network_task_func17hd9a1eeab35a857d1E():
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:83
extern "C" fn network_task_func(_arg: *mut ::cty::c_void) {
   0:	b08e      	sub	sp, #56	; 0x38
_ZN5mylib4base13console_print17h53afd0cf661b2c25E():
/mnt/c/stm32bluepill-mynewt-sensor/src/base.rs:18
        console_buffer(msg.as_ptr(), len as u32);
   2:	f240 0000 	movw	r0, #0
   6:	210a      	movs	r1, #10
   8:	f2c0 0000 	movt	r0, #0
   c:	f7ff fffe 	bl	0 <console_buffer>
/mnt/c/stm32bluepill-mynewt-sensor/src/base.rs:19
        console_flush();  //  TODO: Remove this.
  10:	f7ff fffe 	bl	0 <console_flush>
_ZN5mylib9send_coap17network_task_func17hd9a1eeab35a857d1E():
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:84
    console_print(b"NET start\n");  assert!(unsafe { !NETWORK_IS_READY });
  14:	f240 0400 	movw	r4, #0
  18:	f2c0 0400 	movt	r4, #0
  1c:	7820      	ldrb	r0, [r4, #0]
  1e:	2801      	cmp	r0, #1
  20:	d026      	beq.n	70 <_ZN5mylib9send_coap17network_task_func17hd9a1eeab35a857d1E+0x70>
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:89
        sensor_network::is_standalone_node() || 
  22:	f7ff fffe 	bl	0 <is_standalone_node>
  26:	b910      	cbnz	r0, 8 <is_collector_node+0x8>
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:90
        sensor_network::is_collector_node() 
  28:	f7ff fffe 	bl	0 <is_collector_node>
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:88
    if unsafe { 
  2c:	b120      	cbz	r0, c <register_server_transport+0xc>
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:92
        let rc = unsafe { sensor_network::register_server_transport() };  assert_eq!(rc, 0);
  2e:	f7ff fffe 	bl	0 <register_server_transport>
  32:	2800      	cmp	r0, #0
  34:	9001      	str	r0, [sp, #4]
  36:	d122      	bne.n	7e <_ZN5mylib9send_coap17network_task_func17hd9a1eeab35a857d1E+0x7e>
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:97
        sensor_network::is_collector_node() || 
  38:	f7ff fffe 	bl	0 <is_collector_node>
  3c:	b910      	cbnz	r0, 8 <is_sensor_node+0x8>
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:98
        sensor_network::is_sensor_node() 
  3e:	f7ff fffe 	bl	0 <is_sensor_node>
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:96
    if unsafe { 
  42:	b120      	cbz	r0, c <register_collector_transport+0xc>
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:100
        let rc = unsafe { sensor_network::register_collector_transport() };  assert_eq!(rc, 0);
  44:	f7ff fffe 	bl	0 <register_collector_transport>
  48:	2800      	cmp	r0, #0
  4a:	9001      	str	r0, [sp, #4]
  4c:	d13e      	bne.n	cc <_ZN5mylib9send_coap17network_task_func17hd9a1eeab35a857d1E+0xcc>
  4e:	2001      	movs	r0, #1
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:105
    unsafe { NETWORK_IS_READY = true; }  //  Indicate that network is ready.
  50:	7020      	strb	r0, [r4, #0]
  52:	f240 0400 	movw	r4, #0
  56:	f2c0 0400 	movt	r4, #0
_ZN5mylib4base13console_print17h53afd0cf661b2c25E():
/mnt/c/stm32bluepill-mynewt-sensor/src/base.rs:18
        console_buffer(msg.as_ptr(), len as u32);
  5a:	4620      	mov	r0, r4
  5c:	2111      	movs	r1, #17
  5e:	f7ff fffe 	bl	0 <console_buffer>
/mnt/c/stm32bluepill-mynewt-sensor/src/base.rs:19
        console_flush();  //  TODO: Remove this.
  62:	f7ff fffe 	bl	0 <console_flush>
_ZN5mylib9send_coap17network_task_func17hd9a1eeab35a857d1E():
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:109
        unsafe { os::os_time_delay(10 * os::OS_TICKS_PER_SEC); }                   //  Wait 10 seconds before repeating.
  66:	f242 7010 	movw	r0, #10000	; 0x2710
  6a:	f7ff fffe 	bl	0 <os_time_delay>
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:107
    loop {  //  Loop forever...        
  6e:	e7f4      	b.n	ffffffec <.Lanon.9efeb2f06c0a343721ec0c21943e311a.47+0xffffffe4>
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:84
    console_print(b"NET start\n");  assert!(unsafe { !NETWORK_IS_READY });
  70:	f240 0000 	movw	r0, #0
  74:	f2c0 0000 	movt	r0, #0
  78:	f7ff fffe 	bl	0 <_ZN4core9panicking5panic17h53ca63c6ac6312f8E>
  7c:	defe      	udf	#254	; 0xfe
  7e:	a801      	add	r0, sp, #4
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:92
        let rc = unsafe { sensor_network::register_server_transport() };  assert_eq!(rc, 0);
  80:	900c      	str	r0, [sp, #48]	; 0x30
  82:	f240 0000 	movw	r0, #0
  86:	a90d      	add	r1, sp, #52	; 0x34
  88:	f2c0 0000 	movt	r0, #0
  8c:	900b      	str	r0, [sp, #44]	; 0x2c
  8e:	e9cd 0109 	strd	r0, r1, [sp, #36]	; 0x24
  92:	a80c      	add	r0, sp, #48	; 0x30
  94:	9008      	str	r0, [sp, #32]
  96:	f240 0000 	movw	r0, #0
  9a:	f2c0 0000 	movt	r0, #0
  9e:	f240 0100 	movw	r1, #0
  a2:	900d      	str	r0, [sp, #52]	; 0x34
  a4:	2002      	movs	r0, #2
_ZN4core3fmt9Arguments6new_v117ha99294a9defa432aE():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/fmt/mod.rs:316
  a6:	9007      	str	r0, [sp, #28]
  a8:	a808      	add	r0, sp, #32
  aa:	9006      	str	r0, [sp, #24]
  ac:	2000      	movs	r0, #0
  ae:	e9cd 0004 	strd	r0, r0, [sp, #16]
  b2:	2003      	movs	r0, #3
  b4:	9003      	str	r0, [sp, #12]
  b6:	f240 0000 	movw	r0, #0
  ba:	f2c0 0000 	movt	r0, #0
_ZN5mylib9send_coap17network_task_func17hd9a1eeab35a857d1E():
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:92
  be:	f2c0 0100 	movt	r1, #0
_ZN4core3fmt9Arguments6new_v117ha99294a9defa432aE():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/fmt/mod.rs:316
  c2:	9002      	str	r0, [sp, #8]
  c4:	a802      	add	r0, sp, #8
_ZN5mylib9send_coap17network_task_func17hd9a1eeab35a857d1E():
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:92
  c6:	f7ff fffe 	bl	0 <_ZN4core9panicking9panic_fmt17h6b4d8e87b0965449E>
  ca:	defe      	udf	#254	; 0xfe
  cc:	a801      	add	r0, sp, #4
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:100
        let rc = unsafe { sensor_network::register_collector_transport() };  assert_eq!(rc, 0);
  ce:	900c      	str	r0, [sp, #48]	; 0x30
  d0:	f240 0000 	movw	r0, #0
  d4:	a90d      	add	r1, sp, #52	; 0x34
  d6:	f2c0 0000 	movt	r0, #0
  da:	900b      	str	r0, [sp, #44]	; 0x2c
  dc:	e9cd 0109 	strd	r0, r1, [sp, #36]	; 0x24
  e0:	a80c      	add	r0, sp, #48	; 0x30
  e2:	9008      	str	r0, [sp, #32]
  e4:	f240 0000 	movw	r0, #0
  e8:	f2c0 0000 	movt	r0, #0
  ec:	f240 0100 	movw	r1, #0
  f0:	900d      	str	r0, [sp, #52]	; 0x34
  f2:	2002      	movs	r0, #2
_ZN4core3fmt9Arguments6new_v117ha99294a9defa432aE():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/fmt/mod.rs:316
  f4:	9007      	str	r0, [sp, #28]
  f6:	a808      	add	r0, sp, #32
  f8:	9006      	str	r0, [sp, #24]
  fa:	2000      	movs	r0, #0
  fc:	e9cd 0004 	strd	r0, r0, [sp, #16]
 100:	2003      	movs	r0, #3
 102:	9003      	str	r0, [sp, #12]
 104:	f240 0000 	movw	r0, #0
 108:	f2c0 0000 	movt	r0, #0
_ZN5mylib9send_coap17network_task_func17hd9a1eeab35a857d1E():
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:100
 10c:	f2c0 0100 	movt	r1, #0
_ZN4core3fmt9Arguments6new_v117ha99294a9defa432aE():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/fmt/mod.rs:316
 110:	9002      	str	r0, [sp, #8]
 112:	a802      	add	r0, sp, #8
_ZN5mylib9send_coap17network_task_func17hd9a1eeab35a857d1E():
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:100
 114:	f7ff fffe 	bl	0 <_ZN4core9panicking9panic_fmt17h6b4d8e87b0965449E>
 118:	defe      	udf	#254	; 0xfe

Disassembly of section .text.main:

00000000 <main>:
main():
/mnt/c/stm32bluepill-mynewt-sensor/src/lib.rs:31
use mynewt::kernel::os;         //  Import Mynewt OS API
use crate::base::*;             //  Import `base.rs` for common declarations

///  main() will be called at Mynewt startup. It replaces the C version of the main() function.
#[no_mangle]                     //  Don't mangle the name "main"
pub extern "C" fn main() -> ! {  //  Declare extern "C" because it will be called by Mynewt
   0:	b092      	sub	sp, #72	; 0x48
/mnt/c/stm32bluepill-mynewt-sensor/src/lib.rs:33
    //  Init Mynewt system.
    unsafe { base::rust_sysinit()  };
   2:	f7ff fffe 	bl	0 <rust_sysinit>
/mnt/c/stm32bluepill-mynewt-sensor/src/lib.rs:34
    unsafe { console_flush() };
   6:	f7ff fffe 	bl	0 <console_flush>
_ZN5mylib4base13console_print17h53afd0cf661b2c25E():
/mnt/c/stm32bluepill-mynewt-sensor/src/base.rs:18
        console_buffer(msg.as_ptr(), len as u32);
   a:	f240 0000 	movw	r0, #0
   e:	210a      	movs	r1, #10
  10:	f2c0 0000 	movt	r0, #0
  14:	240a      	movs	r4, #10
  16:	f7ff fffe 	bl	0 <console_buffer>
/mnt/c/stm32bluepill-mynewt-sensor/src/base.rs:19
        console_flush();  //  TODO: Remove this.
  1a:	f7ff fffe 	bl	0 <console_flush>
_ZN5mylib9send_coap18start_network_task17h74bff87eeb41fc59E():
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:63
    let rc = unsafe { os::os_task_init( //  Create a new task and start it...
  1e:	f240 0100 	movw	r1, #0
  22:	f04f 32ff 	mov.w	r2, #4294967295	; 0xffffffff
  26:	f44f 7080 	mov.w	r0, #256	; 0x100
  2a:	f2c0 0100 	movt	r1, #0
  2e:	e9cd 4200 	strd	r4, r2, [sp]
  32:	f240 0200 	movw	r2, #0
  36:	e9cd 1002 	strd	r1, r0, [sp, #8]
  3a:	f240 0000 	movw	r0, #0
  3e:	f240 0100 	movw	r1, #0
  42:	f2c0 0000 	movt	r0, #0
  46:	f2c0 0100 	movt	r1, #0
  4a:	f2c0 0200 	movt	r2, #0
  4e:	2300      	movs	r3, #0
  50:	2400      	movs	r4, #0
  52:	f7ff fffe 	bl	0 <os_task_init>
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:72
    assert_eq!(rc, 0);
  56:	2800      	cmp	r0, #0
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:63
    let rc = unsafe { os::os_task_init( //  Create a new task and start it...
  58:	9009      	str	r0, [sp, #36]	; 0x24
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:72
    assert_eq!(rc, 0);
  5a:	d13f      	bne.n	dc <main+0xdc>
_ZN5mylib4base13console_print17h53afd0cf661b2c25E():
/mnt/c/stm32bluepill-mynewt-sensor/src/base.rs:18
        console_buffer(msg.as_ptr(), len as u32);
  5c:	f240 0000 	movw	r0, #0
  60:	210a      	movs	r1, #10
  62:	f2c0 0000 	movt	r0, #0
  66:	f7ff fffe 	bl	0 <console_buffer>
/mnt/c/stm32bluepill-mynewt-sensor/src/base.rs:19
        console_flush();  //  TODO: Remove this.
  6a:	f7ff fffe 	bl	0 <console_flush>
_ZN5mylib13listen_sensor21start_sensor_listener17h1d9f0c2ac57087e6E():
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:45
    let rc = unsafe { sensor::sensor_set_poll_rate_ms(SENSOR_DEVICE, SENSOR_POLL_TIME) };
  6e:	f240 0000 	movw	r0, #0
  72:	f242 7110 	movw	r1, #10000	; 0x2710
  76:	f2c0 0000 	movt	r0, #0
  7a:	f7ff fffe 	bl	0 <sensor_set_poll_rate_ms>
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:46
    assert_eq!(rc, 0);
  7e:	2800      	cmp	r0, #0
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:45
    let rc = unsafe { sensor::sensor_set_poll_rate_ms(SENSOR_DEVICE, SENSOR_POLL_TIME) };
  80:	9009      	str	r0, [sp, #36]	; 0x24
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:46
    assert_eq!(rc, 0);
  82:	d151      	bne.n	128 <main+0x128>
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:49
    let sensor = unsafe { sensor::sensor_mgr_find_next_bydevname(SENSOR_DEVICE, null_sensor()) };
  84:	f7ff fffe 	bl	0 <null_sensor>
  88:	4601      	mov	r1, r0
  8a:	f240 0000 	movw	r0, #0
  8e:	f2c0 0000 	movt	r0, #0
  92:	f7ff fffe 	bl	0 <sensor_mgr_find_next_bydevname>
  96:	4604      	mov	r4, r0
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:50
    assert!(unsafe{ !is_null_sensor(sensor) });
  98:	f7ff fffe 	bl	0 <is_null_sensor>
  9c:	2800      	cmp	r0, #0
  9e:	d16a      	bne.n	176 <main+0x176>
_ZN5mylib6mynewt2hw6sensor17register_listener17h1dbbbe32ef06507aE():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/hw/sensor.rs:66
    unsafe { assert!(LISTENER_INTERNAL.sl_sensor_type == 0) };  //  Make sure it's not used.
  a0:	f240 0100 	movw	r1, #0
  a4:	f2c0 0100 	movt	r1, #0
  a8:	e9d1 0200 	ldrd	r0, r2, [r1]
  ac:	4310      	orrs	r0, r2
  ae:	d169      	bne.n	184 <main+0x184>
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/hw/sensor.rs:68
    unsafe { LISTENER_INTERNAL = listener };
  b0:	f240 0300 	movw	r3, #0
  b4:	2000      	movs	r0, #0
  b6:	f04f 6280 	mov.w	r2, #67108864	; 0x4000000
  ba:	f04f 0c01 	mov.w	ip, #1
  be:	f2c0 0300 	movt	r3, #0
  c2:	e9c1 2000 	strd	r2, r0, [r1]
  c6:	e9c1 3c02 	strd	r3, ip, [r1, #8]
  ca:	6108      	str	r0, [r1, #16]
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/hw/sensor.rs:70
    unsafe { sensor_register_listener(sensor, &mut LISTENER_INTERNAL) };
  cc:	4620      	mov	r0, r4
  ce:	f7ff fffe 	bl	0 <sensor_register_listener>
main():
/mnt/c/stm32bluepill-mynewt-sensor/src/lib.rs:52

    //  Main event loop
    loop {                            //  Loop forever...
        unsafe {
            os::os_eventq_run(            //  Process events...
                os::os_eventq_dflt_get()  //  From default event queue.
  d2:	f7ff fffe 	bl	0 <os_eventq_dflt_get>
/mnt/c/stm32bluepill-mynewt-sensor/src/lib.rs:51
            os::os_eventq_run(            //  Process events...
  d6:	f7ff fffe 	bl	0 <os_eventq_run>
/mnt/c/stm32bluepill-mynewt-sensor/src/lib.rs:49
    loop {                            //  Loop forever...
  da:	e7fa      	b.n	d2 <main+0xd2>
  dc:	a809      	add	r0, sp, #36	; 0x24
_ZN5mylib9send_coap18start_network_task17h74bff87eeb41fc59E():
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:72
  de:	9010      	str	r0, [sp, #64]	; 0x40
  e0:	f240 0000 	movw	r0, #0
  e4:	a911      	add	r1, sp, #68	; 0x44
  e6:	f2c0 0000 	movt	r0, #0
  ea:	9008      	str	r0, [sp, #32]
  ec:	e9cd 0106 	strd	r0, r1, [sp, #24]
  f0:	a810      	add	r0, sp, #64	; 0x40
  f2:	9005      	str	r0, [sp, #20]
  f4:	f240 0000 	movw	r0, #0
  f8:	f2c0 0000 	movt	r0, #0
  fc:	f240 0100 	movw	r1, #0
 100:	9011      	str	r0, [sp, #68]	; 0x44
 102:	2002      	movs	r0, #2
_ZN4core3fmt9Arguments6new_v117ha99294a9defa432aE():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/fmt/mod.rs:316
 104:	900f      	str	r0, [sp, #60]	; 0x3c
 106:	a805      	add	r0, sp, #20
 108:	900e      	str	r0, [sp, #56]	; 0x38
 10a:	2003      	movs	r0, #3
 10c:	e9cd 440c 	strd	r4, r4, [sp, #48]	; 0x30
_ZN5mylib9send_coap18start_network_task17h74bff87eeb41fc59E():
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:72
 110:	f2c0 0100 	movt	r1, #0
_ZN4core3fmt9Arguments6new_v117ha99294a9defa432aE():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/fmt/mod.rs:316
 114:	900b      	str	r0, [sp, #44]	; 0x2c
 116:	f240 0000 	movw	r0, #0
 11a:	f2c0 0000 	movt	r0, #0
 11e:	900a      	str	r0, [sp, #40]	; 0x28
 120:	a80a      	add	r0, sp, #40	; 0x28
_ZN5mylib9send_coap18start_network_task17h74bff87eeb41fc59E():
/mnt/c/stm32bluepill-mynewt-sensor/src/send_coap.rs:72
 122:	f7ff fffe 	bl	0 <_ZN4core9panicking9panic_fmt17h6b4d8e87b0965449E>
 126:	defe      	udf	#254	; 0xfe
main():
 128:	a809      	add	r0, sp, #36	; 0x24
_ZN5mylib13listen_sensor21start_sensor_listener17h1d9f0c2ac57087e6E():
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:46
    assert_eq!(rc, 0);
 12a:	9010      	str	r0, [sp, #64]	; 0x40
 12c:	f240 0000 	movw	r0, #0
 130:	a911      	add	r1, sp, #68	; 0x44
 132:	f2c0 0000 	movt	r0, #0
 136:	9008      	str	r0, [sp, #32]
 138:	e9cd 0106 	strd	r0, r1, [sp, #24]
 13c:	a810      	add	r0, sp, #64	; 0x40
 13e:	9005      	str	r0, [sp, #20]
 140:	f240 0000 	movw	r0, #0
 144:	f2c0 0000 	movt	r0, #0
 148:	f240 0100 	movw	r1, #0
 14c:	9011      	str	r0, [sp, #68]	; 0x44
 14e:	2002      	movs	r0, #2
_ZN4core3fmt9Arguments6new_v117ha99294a9defa432aE():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/fmt/mod.rs:316
 150:	900f      	str	r0, [sp, #60]	; 0x3c
 152:	a805      	add	r0, sp, #20
 154:	900e      	str	r0, [sp, #56]	; 0x38
 156:	2000      	movs	r0, #0
 158:	e9cd 000c 	strd	r0, r0, [sp, #48]	; 0x30
 15c:	2003      	movs	r0, #3
 15e:	900b      	str	r0, [sp, #44]	; 0x2c
 160:	f240 0000 	movw	r0, #0
 164:	f2c0 0000 	movt	r0, #0
_ZN5mylib13listen_sensor21start_sensor_listener17h1d9f0c2ac57087e6E():
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:46
 168:	f2c0 0100 	movt	r1, #0
_ZN4core3fmt9Arguments6new_v117ha99294a9defa432aE():
/rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/fmt/mod.rs:316
 16c:	900a      	str	r0, [sp, #40]	; 0x28
 16e:	a80a      	add	r0, sp, #40	; 0x28
_ZN5mylib13listen_sensor21start_sensor_listener17h1d9f0c2ac57087e6E():
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:46
 170:	f7ff fffe 	bl	0 <_ZN4core9panicking9panic_fmt17h6b4d8e87b0965449E>
 174:	defe      	udf	#254	; 0xfe
/mnt/c/stm32bluepill-mynewt-sensor/src/listen_sensor.rs:50
    assert!(unsafe{ !is_null_sensor(sensor) });
 176:	f240 0000 	movw	r0, #0
 17a:	f2c0 0000 	movt	r0, #0
 17e:	f7ff fffe 	bl	0 <_ZN4core9panicking5panic17h53ca63c6ac6312f8E>
 182:	defe      	udf	#254	; 0xfe
_ZN5mylib6mynewt2hw6sensor17register_listener17h1dbbbe32ef06507aE():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt/hw/sensor.rs:66
    unsafe { assert!(LISTENER_INTERNAL.sl_sensor_type == 0) };  //  Make sure it's not used.
 184:	f240 0000 	movw	r0, #0
 188:	f2c0 0000 	movt	r0, #0
 18c:	f7ff fffe 	bl	0 <_ZN4core9panicking5panic17h53ca63c6ac6312f8E>
 190:	defe      	udf	#254	; 0xfe

Disassembly of section .text.rust_begin_unwind:

00000000 <rust_begin_unwind>:
rust_begin_unwind():
/mnt/c/stm32bluepill-mynewt-sensor/src/lib.rs:63

///  This function is called on panic, like an assertion failure. We display the filename and line number and pause in the debugger. From https://os.phil-opp.com/freestanding-rust-binary/
#[panic_handler]
fn panic(info: &PanicInfo) -> ! {
    //  Display the filename and line number to the Semihosting Console.
    if let Some(location) = info.location() {
   0:	f7ff fffe 	bl	0 <_ZN4core5panic9PanicInfo8location17h5226165d8771f8a2E>
   4:	b338      	cbz	r0, 56 <rust_begin_unwind+0x56>
   6:	4604      	mov	r4, r0
/mnt/c/stm32bluepill-mynewt-sensor/src/lib.rs:64
        let file = location.file();
   8:	f7ff fffe 	bl	0 <_ZN4core5panic8Location4file17h94cc6af18de736c4E>
   c:	4605      	mov	r5, r0
/mnt/c/stm32bluepill-mynewt-sensor/src/lib.rs:65
        let line = location.line();
   e:	4620      	mov	r0, r4
/mnt/c/stm32bluepill-mynewt-sensor/src/lib.rs:64
        let file = location.file();
  10:	460e      	mov	r6, r1
/mnt/c/stm32bluepill-mynewt-sensor/src/lib.rs:65
        let line = location.line();
  12:	f7ff fffe 	bl	0 <_ZN4core5panic8Location4line17h3ffc63f14d0a6636E>
  16:	4604      	mov	r4, r0
_ZN5mylib4base13console_print17h53afd0cf661b2c25E():
/mnt/c/stm32bluepill-mynewt-sensor/src/base.rs:18
        console_buffer(msg.as_ptr(), len as u32);
  18:	f240 0000 	movw	r0, #0
  1c:	f2c0 0000 	movt	r0, #0
  20:	2109      	movs	r1, #9
  22:	f7ff fffe 	bl	0 <console_buffer>
/mnt/c/stm32bluepill-mynewt-sensor/src/base.rs:19
        console_flush();  //  TODO: Remove this.
  26:	f7ff fffe 	bl	0 <console_flush>
rust_begin_unwind():
/mnt/c/stm32bluepill-mynewt-sensor/src/lib.rs:67
        console_print(b"panic at ");
        unsafe { console_buffer(file.as_ptr(), file.len() as u32) }
  2a:	4628      	mov	r0, r5
  2c:	4631      	mov	r1, r6
  2e:	f7ff fffe 	bl	0 <console_buffer>
_ZN5mylib4base13console_print17h53afd0cf661b2c25E():
/mnt/c/stm32bluepill-mynewt-sensor/src/base.rs:18
        console_buffer(msg.as_ptr(), len as u32);
  32:	f240 0000 	movw	r0, #0
  36:	2108      	movs	r1, #8
  38:	f2c0 0000 	movt	r0, #0
  3c:	f7ff fffe 	bl	0 <console_buffer>
/mnt/c/stm32bluepill-mynewt-sensor/src/base.rs:19
        console_flush();  //  TODO: Remove this.
  40:	f7ff fffe 	bl	0 <console_flush>
rust_begin_unwind():
/mnt/c/stm32bluepill-mynewt-sensor/src/lib.rs:69
        console_print(b" line 0x");
        unsafe { console_printhex(line as u8) }  //  TODO: Print in decimal not hex. Allow more than 255 lines.
  44:	b2e0      	uxtb	r0, r4
  46:	f7ff fffe 	bl	0 <console_printhex>
_ZN5mylib4base13console_print17h53afd0cf661b2c25E():
/mnt/c/stm32bluepill-mynewt-sensor/src/base.rs:18
        console_buffer(msg.as_ptr(), len as u32);
  4a:	f240 0000 	movw	r0, #0
  4e:	2101      	movs	r1, #1
  50:	f2c0 0000 	movt	r0, #0
  54:	e004      	b.n	c <rust_begin_unwind+0xc>
  56:	f240 0000 	movw	r0, #0
  5a:	2112      	movs	r1, #18
  5c:	f2c0 0000 	movt	r0, #0
rust_begin_unwind():
  60:	f7ff fffe 	bl	0 <console_buffer>
  64:	f7ff fffe 	bl	0 <console_flush>
  68:	f7ff fffe 	bl	0 <console_flush>
_ZN8cortex_m3asm4bkpt17hc1862ddcb43450fcE():
/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-0.6.0/src/asm.rs:19
        () => unsafe {
            extern "C" {
                fn __bkpt();
            }

            __bkpt();
  6c:	f7ff fffe 	bl	0 <__bkpt>
rust_begin_unwind():
/mnt/c/stm32bluepill-mynewt-sensor/src/lib.rs:79
        unsafe { console_flush() }
    }
    //  Pause in the debugger.
    bkpt();
    //  Loop forever so that device won't restart.
    loop {}
  70:	e7fe      	b.n	70 <rust_begin_unwind+0x70>

Disassembly of section .text._ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE:

00000000 <_ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE>:
_ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE():
/mnt/c/stm32bluepill-mynewt-sensor/src/mynewt.rs:30
    #[derive(Debug, PartialEq)]
   0:	b510      	push	{r4, lr}
   2:	b084      	sub	sp, #16
   4:	6802      	ldr	r2, [r0, #0]
   6:	f102 000f 	add.w	r0, r2, #15
   a:	280e      	cmp	r0, #14
   c:	d80f      	bhi.n	2e <_ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE+0x2e>
   e:	e8df f000 	tbb	[pc, r0]
  12:	1908      	.short	0x1908
  14:	352f2721 	.word	0x352f2721
  18:	4f49413b 	.word	0x4f49413b
  1c:	69615b55 	.word	0x69615b55
  20:	006f      	.short	0x006f
  22:	f240 0200 	movw	r2, #0
  26:	ac01      	add	r4, sp, #4
  28:	f2c0 0200 	movt	r2, #0
  2c:	e037      	b.n	9e <_ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE+0x9e>
  2e:	2001      	movs	r0, #1
  30:	ac01      	add	r4, sp, #4
  32:	f6cf 70ff 	movt	r0, #65535	; 0xffff
  36:	4282      	cmp	r2, r0
  38:	d162      	bne.n	100 <_ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE+0x100>
  3a:	f240 0200 	movw	r2, #0
  3e:	f2c0 0200 	movt	r2, #0
  42:	e04c      	b.n	de <_ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE+0xde>
  44:	ac01      	add	r4, sp, #4
  46:	f240 0200 	movw	r2, #0
  4a:	f2c0 0200 	movt	r2, #0
  4e:	230d      	movs	r3, #13
  50:	4620      	mov	r0, r4
  52:	e05b      	b.n	10c <_ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE+0x10c>
  54:	f240 0200 	movw	r2, #0
  58:	ac01      	add	r4, sp, #4
  5a:	f2c0 0200 	movt	r2, #0
  5e:	e03e      	b.n	de <_ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE+0xde>
  60:	ac01      	add	r4, sp, #4
  62:	f240 0200 	movw	r2, #0
  66:	f2c0 0200 	movt	r2, #0
  6a:	230b      	movs	r3, #11
  6c:	4620      	mov	r0, r4
  6e:	e04d      	b.n	10c <_ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE+0x10c>
  70:	f240 0200 	movw	r2, #0
  74:	ac01      	add	r4, sp, #4
  76:	f2c0 0200 	movt	r2, #0
  7a:	e030      	b.n	64 <_ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE+0x64>
  7c:	f240 0200 	movw	r2, #0
  80:	ac01      	add	r4, sp, #4
  82:	f2c0 0200 	movt	r2, #0
  86:	e038      	b.n	74 <_ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE+0x74>
  88:	f240 0200 	movw	r2, #0
  8c:	ac01      	add	r4, sp, #4
  8e:	f2c0 0200 	movt	r2, #0
  92:	e032      	b.n	68 <_ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE+0x68>
  94:	f240 0200 	movw	r2, #0
  98:	ac01      	add	r4, sp, #4
  9a:	f2c0 0200 	movt	r2, #0
  9e:	4620      	mov	r0, r4
  a0:	2309      	movs	r3, #9
  a2:	e033      	b.n	10c <_ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE+0x10c>
  a4:	f240 0200 	movw	r2, #0
  a8:	ac01      	add	r4, sp, #4
  aa:	f2c0 0200 	movt	r2, #0
  ae:	e024      	b.n	4c <_ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE+0x4c>
  b0:	f240 0200 	movw	r2, #0
  b4:	ac01      	add	r4, sp, #4
  b6:	f2c0 0200 	movt	r2, #0
  ba:	e01e      	b.n	40 <_ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE+0x40>
  bc:	f240 0200 	movw	r2, #0
  c0:	ac01      	add	r4, sp, #4
  c2:	f2c0 0200 	movt	r2, #0
  c6:	e01f      	b.n	42 <_ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE+0x42>
  c8:	f240 0200 	movw	r2, #0
  cc:	ac01      	add	r4, sp, #4
  ce:	f2c0 0200 	movt	r2, #0
  d2:	e012      	b.n	28 <_ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE+0x28>
  d4:	f240 0200 	movw	r2, #0
  d8:	ac01      	add	r4, sp, #4
  da:	f2c0 0200 	movt	r2, #0
  de:	4620      	mov	r0, r4
  e0:	230c      	movs	r3, #12
  e2:	e013      	b.n	10c <_ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE+0x10c>
  e4:	f240 0200 	movw	r2, #0
  e8:	ac01      	add	r4, sp, #4
  ea:	f2c0 0200 	movt	r2, #0
  ee:	e004      	b.n	c <_ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE+0xc>
  f0:	f240 0200 	movw	r2, #0
  f4:	ac01      	add	r4, sp, #4
  f6:	f2c0 0200 	movt	r2, #0
  fa:	4620      	mov	r0, r4
  fc:	230a      	movs	r3, #10
  fe:	e005      	b.n	10c <_ZN71_$LT$mylib..mynewt..result..MynewtError$u20$as$u20$core..fmt..Debug$GT$3fmt17he637fff21126bd1cE+0x10c>
 100:	f240 0200 	movw	r2, #0
 104:	f2c0 0200 	movt	r2, #0
 108:	4620      	mov	r0, r4
 10a:	2307      	movs	r3, #7
 10c:	f7ff fffe 	bl	0 <_ZN4core3fmt9Formatter11debug_tuple17h793087e8ecab9022E>
 110:	4620      	mov	r0, r4
 112:	f7ff fffe 	bl	0 <_ZN4core3fmt8builders10DebugTuple6finish17h24d91625b3672e6dE>
 116:	b004      	add	sp, #16
 118:	bd10      	pop	{r4, pc}
arm-none-eabi-objdump: rust.metadata.bin: file format not recognized
arm-none-eabi-objdump: mylib-9b5f404664613177.mylib.9ieylas6-cgu.0.rcgu.bc.z: file format not recognized
