//!  Contains Rust Bindings for Mynewt C API, generated by `bindgen`
#![no_std]                  //  Don't link with standard Rust library, which is not compatible with embedded systems
#![feature(trace_macros)]   //  To support macro tracing: trace_macros!(true)
#![feature(concat_idents)]  //  To support concat_idents!() macro used in coap!() macro

pub mod tinycbor;       //  Export tinycbor.rs as Rust module `tinycbor`
pub mod sensor;         //  Export sensor.rs as Rust module `sensor`
pub mod sensor_network; //  Export sensor_network.rs as Rust module `sensor_network`
