//!  Rust Bindings for Mynewt C API, generated by `bindgen`

#[macro_use]            //  Allow macros from Rust module `macros`
pub mod macros;         //  Export `macros.rs` as Rust module `macros`. Contains Mynewt macros.

//  encoding/*: Encoding Libraries
pub mod tinycbor;       //  Export `tinycbor.rs` as Rust module `tinycbor`. Contains Rust bindings for Mynewt Encoding Library `encoding/tinycbor`.
pub mod json;           //  Export `json.rs` as Rust module `json`. Contains Rust bindings for Mynewt Encoding Library `encoding/json`.

//  kernel/*: Kernel API
pub mod os;             //  Export `os.rs` as Rust module `os`. Contains Rust bindings for Mynewt OS API `kernel/os`.

//  hw/*: Hardware API
pub mod sensor;         //  Export `sensor.rs` as Rust module `sensor`.  Contains Rust bindings for Mynewt Sensor API `hw/sensor`.

//  libs/*: Custom Libraries
pub mod sensor_coap;    //  Export `sensor_coap.rs` as Rust module `sensor_coap`.  Contains Rust bindings for Mynewt Custom Library `libs/sensor_coap`.
pub mod sensor_network; //  Export `sensor_network.rs` as Rust module `sensor_network`.  Contains Rust bindings for Mynewt Custom Library `libs/sensor_network`.

///  Defined in repos/apache-mynewt-core/net/oic/src/api/oc_rep.c
#[link(name = "net_oic")]
extern {
    pub static mut g_encoder: tinycbor::CborEncoder;
    pub static mut root_map: tinycbor::CborEncoder;
}
